// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.battle

object BattleProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      protocol.battle.S2C_SetUserID,
      protocol.battle.S2C_C2S_UnitMoveInfo,
      protocol.battle.S2C_UnitInfo,
      protocol.battle.S2C_UnitInfos,
      protocol.battle.S2C_UseSkill,
      protocol.battle.S2C_DestroyUnit,
      protocol.battle.S2C_OneLand,
      protocol.battle.S2C_AllLands,
      protocol.battle.S2C_LeftLimit,
      protocol.battle.C2S_HB,
      protocol.battle.C2S_UseSkill,
      protocol.battle.C2S_ChangeInputDir
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgxiYXR0bGUucHJvdG8SCHByb3RvY29sIigKDVMyQ19TZXRVc2VySUQSFwoCSUQYASACKAVCB+I/BBICaURSAklEIrECChRTM
  kNfQzJTX1VuaXRNb3ZlSW5mbxIsCglQb3NTdGF0dXMYASACKAVCDuI/CxIJcG9zU3RhdHVzUglQb3NTdGF0dXMSOwoOTGFuZE9yT
  GFkZGVySUQYAiACKAVCE+I/EBIObGFuZE9yTGFkZGVySURSDkxhbmRPckxhZGRlcklEEh0KBFBvc1gYAyACKAJCCeI/BhIEcG9zW
  FIEUG9zWBIdCgRQb3NZGAQgAigCQgniPwYSBHBvc1lSBFBvc1kSIwoGU3BlZWRYGAUgAigCQgviPwgSBnNwZWVkWFIGU3BlZWRYE
  iMKBlNwZWVkWRgGIAIoAkIL4j8IEgZzcGVlZFlSBlNwZWVkWRImCgdGYWNlRGlyGAcgAigCQgziPwkSB2ZhY2VEaXJSB0ZhY2VEa
  XIi8QMKDFMyQ19Vbml0SW5mbxIXCgJJRBgBIAIoBUIH4j8EEgJpRFICSUQSKQoIVW5pdFR5cGUYAiACKAVCDeI/ChIIdW5pdFR5c
  GVSCFVuaXRUeXBlEjgKDUNvbnRyb2xQbGF5ZXIYAyACKAVCEuI/DxINY29udHJvbFBsYXllclINQ29udHJvbFBsYXllchIyCgtIY
  W5kQ29udHJvbBgEIAIoCEIQ4j8NEgtoYW5kQ29udHJvbFILSGFuZENvbnRyb2wSIwoGSHBSYXRlGAUgAigCQgviPwgSBmhwUmF0Z
  VIGSHBSYXRlEiMKBk1wUmF0ZRgKIAIoAkIL4j8IEgZtcFJhdGVSBk1wUmF0ZRIpCghOb3dJbnB1dBgGIAIoCEIN4j8KEghub3dJb
  nB1dFIITm93SW5wdXQSMgoLTm93SW5wdXREaXIYByACKAJCEOI/DRILbm93SW5wdXREaXJSC05vd0lucHV0RGlyEi8KClJhbmRvb
  VNlZWQYCCACKAVCD+I/DBIKcmFuZG9tU2VlZFIKUmFuZG9tU2VlZBJVCgxVbml0TW92ZUluZm8YCSACKAsyHi5wcm90b2NvbC5TM
  kNfQzJTX1VuaXRNb3ZlSW5mb0IR4j8OEgx1bml0TW92ZUluZm9SDFVuaXRNb3ZlSW5mbyJVCg1TMkNfVW5pdEluZm9zEkQKCVVua
  XRJbmZvcxgBIAMoCzIWLnByb3RvY29sLlMyQ19Vbml0SW5mb0IO4j8LEgl1bml0SW5mb3NSCVVuaXRJbmZvcyJbCgxTMkNfVXNlU
  2tpbGwSIwoGVW5pdElEGAEgAigFQgviPwgSBnVuaXRJRFIGVW5pdElEEiYKB1NraWxsSUQYAiACKAVCDOI/CRIHc2tpbGxJRFIHU
  2tpbGxJRCI2Cg9TMkNfRGVzdHJveVVuaXQSIwoGVW5pdElEGAEgAigFQgviPwgSBnVuaXRJRFIGVW5pdElEIpwCCgtTMkNfT25lT
  GFuZBIXCgJJRBgBIAIoBUIH4j8EEgJpRFICSUQSIAoFTGVmdFgYAiACKAJCCuI/BxIFbGVmdFhSBUxlZnRYEiAKBUxlZnRZGAMgA
  igCQgriPwcSBWxlZnRZUgVMZWZ0WRIjCgZSaWdodFgYBCACKAJCC+I/CBIGcmlnaHRYUgZSaWdodFgSIwoGUmlnaHRZGAUgAigCQ
  gviPwgSBnJpZ2h0WVIGUmlnaHRZEi8KCkNhbkNyb3NzVXAYBiACKAhCD+I/DBIKY2FuQ3Jvc3NVcFIKQ2FuQ3Jvc3NVcBI1CgxDY
  W5Dcm9zc0Rvd24YByACKAhCEeI/DhIMY2FuQ3Jvc3NEb3duUgxDYW5Dcm9zc0Rvd24iRwoMUzJDX0FsbExhbmRzEjcKBUxhbmRzG
  AEgAygLMhUucHJvdG9jb2wuUzJDX09uZUxhbmRCCuI/BxIFbGFuZHNSBUxhbmRzIj0KDVMyQ19MZWZ0TGltaXQSLAoJTGVmdExpb
  Wl0GAEgAigFQg7iPwsSCWxlZnRMaW1pdFIJTGVmdExpbWl0IggKBkMyU19IQiKNAQoMQzJTX1VzZVNraWxsEiYKB1NraWxsSUQYA
  SACKAVCDOI/CRIHc2tpbGxJRFIHU2tpbGxJRBJVCgxVbml0TW92ZUluZm8YAiACKAsyHi5wcm90b2NvbC5TMkNfQzJTX1VuaXRNb
  3ZlSW5mb0IR4j8OEgx1bml0TW92ZUluZm9SDFVuaXRNb3ZlSW5mbyJzChJDMlNfQ2hhbmdlSW5wdXREaXISKQoITm93SW5wdXQYA
  SACKAhCDeI/ChIIbm93SW5wdXRSCE5vd0lucHV0EjIKC05vd0lucHV0RGlyGAIgAigCQhDiPw0SC25vd0lucHV0RGlyUgtOb3dJb
  nB1dERpcg=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor =
    protocol.Battle.getDescriptor()
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}