// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.bag
import _root_.scalapb.internal.compat.JavaConverters._

/** 推送背包列表（完整的）
  *
  * @param bags
  *   背包列表
  */
@SerialVersionUID(0L)
final case class SC11200(
    bags: _root_.scala.Seq[protocol.bag.BagInfo] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SC11200] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      bags.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      bags.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearBags = copy(bags = _root_.scala.Seq.empty)
    def addBags(__vs: protocol.bag.BagInfo*): SC11200 = addAllBags(__vs)
    def addAllBags(__vs: Iterable[protocol.bag.BagInfo]): SC11200 = copy(bags = bags ++ __vs)
    def withBags(__v: _root_.scala.Seq[protocol.bag.BagInfo]): SC11200 = copy(bags = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => bags
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(bags.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = protocol.bag.SC11200
    // @@protoc_insertion_point(GeneratedMessage[protocol.SC11200])
}

object SC11200 extends scalapb.GeneratedMessageCompanion[protocol.bag.SC11200] with scalapb.HasBuilder[protocol.bag.SC11200] with scalapb.JavaProtoSupport[protocol.bag.SC11200, protocol.Bag.SC11200] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[protocol.bag.SC11200] with scalapb.HasBuilder[protocol.bag.SC11200] with scalapb.JavaProtoSupport[protocol.bag.SC11200, protocol.Bag.SC11200] = this
  def toJavaProto(scalaPbSource: protocol.bag.SC11200): protocol.Bag.SC11200 = {
    val javaPbOut = protocol.Bag.SC11200.newBuilder
    javaPbOut.addAllBags(_root_.scalapb.internal.compat.toIterable(scalaPbSource.bags.iterator.map(protocol.bag.BagInfo.toJavaProto(_))).asJava)
    javaPbOut.build
  }
  def fromJavaProto(javaPbSource: protocol.Bag.SC11200): protocol.bag.SC11200 = protocol.bag.SC11200(
    bags = javaPbSource.getBagsList.asScala.iterator.map(protocol.bag.BagInfo.fromJavaProto(_)).toSeq
  )
  def merge(`_message__`: protocol.bag.SC11200, `_input__`: _root_.com.google.protobuf.CodedInputStream): protocol.bag.SC11200 = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[protocol.bag.SC11200] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      protocol.bag.SC11200(
        bags = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[protocol.bag.BagInfo]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = BagProto.javaDescriptor.getMessageTypes().get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = BagProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = protocol.bag.BagInfo
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = protocol.bag.SC11200(
    bags = _root_.scala.Seq.empty
  )
  final class Builder private (
    private val __bags: _root_.scala.collection.immutable.VectorBuilder[protocol.bag.BagInfo],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[protocol.bag.SC11200] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __bags += _root_.scalapb.LiteParser.readMessage[protocol.bag.BagInfo](_input__)
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): protocol.bag.SC11200 = {
      protocol.bag.SC11200(
        bags = __bags.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[protocol.bag.SC11200, protocol.bag.SC11200.Builder] {
    def apply(): Builder = new Builder(
      __bags = new _root_.scala.collection.immutable.VectorBuilder[protocol.bag.BagInfo],
      `_unknownFields__` = null
    )
    def apply(`_message__`: protocol.bag.SC11200): Builder = new Builder(
        __bags = new _root_.scala.collection.immutable.VectorBuilder[protocol.bag.BagInfo] ++= _message__.bags,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = protocol.bag.SC11200.Builder()
  def newBuilder(`_message__`: protocol.bag.SC11200): Builder = protocol.bag.SC11200.Builder(_message__)
  implicit class SC11200Lens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, protocol.bag.SC11200]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, protocol.bag.SC11200](_l) {
    def bags: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[protocol.bag.BagInfo]] = field(_.bags)((c_, f_) => c_.copy(bags = f_))
  }
  final val BAGS_FIELD_NUMBER = 1
  def of(
    bags: _root_.scala.Seq[protocol.bag.BagInfo]
  ): _root_.protocol.bag.SC11200 = _root_.protocol.bag.SC11200(
    bags
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[protocol.SC11200])
}
