// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.user

object UserProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    protocol.base.BaseProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      protocol.user.CS10010,
      protocol.user.SC10010,
      protocol.user.CS10011,
      protocol.user.SC10011
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cgp1c2VyLnByb3RvEghwcm90b2NvbBoKYmFzZS5wcm90byJnCgdDUzEwMDEwEj0KB2FjY291bnQYASACKAsyFS5wcm90b2Nvb
  C5BY2NvdW50SW5mb0IM4j8JEgdhY2NvdW50UgdhY2NvdW50Eh0KBG5hbWUYAiACKAlCCeI/BhIEbmFtZVIEbmFtZSJZCgdTQzEwM
  DEwEiYKB3N1Y2Nlc3MYASACKAhCDOI/CRIHc3VjY2Vzc1IHc3VjY2VzcxImCgdjb250ZW50GAIgASgJQgziPwkSB2NvbnRlbnRSB
  2NvbnRlbnQiSAoHQ1MxMDAxMRI9CgdhY2NvdW50GAEgAigLMhUucHJvdG9jb2wuQWNjb3VudEluZm9CDOI/CRIHYWNjb3VudFIHY
  WNjb3VudCJ+CgdTQzEwMDExEiYKB3N1Y2Nlc3MYASACKAhCDOI/CRIHc3VjY2Vzc1IHc3VjY2VzcxIjCgZ1c2VySWQYAiABKANCC
  +I/CBIGdXNlcklkUgZ1c2VySWQSJgoHY29udGVudBgDIAEoCUIM4j8JEgdjb250ZW50Ugdjb250ZW50"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor =
    protocol.User.getDescriptor()
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}