// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.scene

/** @param face
 * 面部朝向(0代表看向右边(默认),1代表看向左边)
 */
@SerialVersionUID(0L)
final case class JumpInfo(
                           positionX: _root_.scala.Float,
                           positionY: _root_.scala.Float,
                           highestPosX: _root_.scala.Float,
                           highestPosY: _root_.scala.Float,
                           finalPosX: _root_.scala.Float,
                           finalPosY: _root_.scala.Float,
                           face: _root_.scala.Float,
                           unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
                         ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[JumpInfo] {
  @transient
  private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0

  private[this] def __computeSerializedValue(): _root_.scala.Int = {
    var __size = 0

    {
      val __value = positionX
      __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(1, __value)
    };

    {
      val __value = positionY
      __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(2, __value)
    };

    {
      val __value = highestPosX
      __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(3, __value)
    };

    {
      val __value = highestPosY
      __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(4, __value)
    };

    {
      val __value = finalPosX
      __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(5, __value)
    };

    {
      val __value = finalPosY
      __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(6, __value)
    };

    {
      val __value = face
      __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(7, __value)
    };
    __size += unknownFields.serializedSize
    __size
  }

  override def serializedSize: _root_.scala.Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {

    {
      val __v = positionX
      _output__.writeFloat(1, __v)
    };

    {
      val __v = positionY
      _output__.writeFloat(2, __v)
    };

    {
      val __v = highestPosX
      _output__.writeFloat(3, __v)
    };

    {
      val __v = highestPosY
      _output__.writeFloat(4, __v)
    };

    {
      val __v = finalPosX
      _output__.writeFloat(5, __v)
    };

    {
      val __v = finalPosY
      _output__.writeFloat(6, __v)
    };

    {
      val __v = face
      _output__.writeFloat(7, __v)
    };
    unknownFields.writeTo(_output__)
  }

  def withPositionX(__v: _root_.scala.Float): JumpInfo = copy(positionX = __v)

  def withPositionY(__v: _root_.scala.Float): JumpInfo = copy(positionY = __v)

  def withHighestPosX(__v: _root_.scala.Float): JumpInfo = copy(highestPosX = __v)

  def withHighestPosY(__v: _root_.scala.Float): JumpInfo = copy(highestPosY = __v)

  def withFinalPosX(__v: _root_.scala.Float): JumpInfo = copy(finalPosX = __v)

  def withFinalPosY(__v: _root_.scala.Float): JumpInfo = copy(finalPosY = __v)

  def withFace(__v: _root_.scala.Float): JumpInfo = copy(face = __v)

  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)

  def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => positionX
      case 2 => positionY
      case 3 => highestPosX
      case 4 => highestPosY
      case 5 => finalPosX
      case 6 => finalPosY
      case 7 => face
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @_root_.scala.unchecked) match {
      case 1 => _root_.scalapb.descriptors.PFloat(positionX)
      case 2 => _root_.scalapb.descriptors.PFloat(positionY)
      case 3 => _root_.scalapb.descriptors.PFloat(highestPosX)
      case 4 => _root_.scalapb.descriptors.PFloat(highestPosY)
      case 5 => _root_.scalapb.descriptors.PFloat(finalPosX)
      case 6 => _root_.scalapb.descriptors.PFloat(finalPosY)
      case 7 => _root_.scalapb.descriptors.PFloat(face)
    }
  }

  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)

  def companion = protocol.scene.JumpInfo
  // @@protoc_insertion_point(GeneratedMessage[protocol.JumpInfo])
}

object JumpInfo extends scalapb.GeneratedMessageCompanion[protocol.scene.JumpInfo] with scalapb.HasBuilder[protocol.scene.JumpInfo] with scalapb.JavaProtoSupport[protocol.scene.JumpInfo, protocol.Scene.JumpInfo] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[protocol.scene.JumpInfo] with scalapb.HasBuilder[protocol.scene.JumpInfo] with scalapb.JavaProtoSupport[protocol.scene.JumpInfo, protocol.Scene.JumpInfo] = this

  def toJavaProto(scalaPbSource: protocol.scene.JumpInfo): protocol.Scene.JumpInfo = {
    val javaPbOut = protocol.Scene.JumpInfo.newBuilder
    javaPbOut.setPositionX(scalaPbSource.positionX)
    javaPbOut.setPositionY(scalaPbSource.positionY)
    javaPbOut.setHighestPosX(scalaPbSource.highestPosX)
    javaPbOut.setHighestPosY(scalaPbSource.highestPosY)
    javaPbOut.setFinalPosX(scalaPbSource.finalPosX)
    javaPbOut.setFinalPosY(scalaPbSource.finalPosY)
    javaPbOut.setFace(scalaPbSource.face)
    javaPbOut.build
  }

  def fromJavaProto(javaPbSource: protocol.Scene.JumpInfo): protocol.scene.JumpInfo = protocol.scene.JumpInfo(
    positionX = javaPbSource.getPositionX.floatValue,
    positionY = javaPbSource.getPositionY.floatValue,
    highestPosX = javaPbSource.getHighestPosX.floatValue,
    highestPosY = javaPbSource.getHighestPosY.floatValue,
    finalPosX = javaPbSource.getFinalPosX.floatValue,
    finalPosY = javaPbSource.getFinalPosY.floatValue,
    face = javaPbSource.getFace.floatValue
  )

  def merge(`_message__`: protocol.scene.JumpInfo, `_input__`: _root_.com.google.protobuf.CodedInputStream): protocol.scene.JumpInfo = newBuilder(_message__).merge(_input__).result()

  implicit def messageReads: _root_.scalapb.descriptors.Reads[protocol.scene.JumpInfo] = _root_.scalapb.descriptors.Reads {
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      protocol.scene.JumpInfo(
        positionX = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).get.as[_root_.scala.Float],
        positionY = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).get.as[_root_.scala.Float],
        highestPosX = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).get.as[_root_.scala.Float],
        highestPosY = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).get.as[_root_.scala.Float],
        finalPosX = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).get.as[_root_.scala.Float],
        finalPosY = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).get.as[_root_.scala.Float],
        face = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).get.as[_root_.scala.Float]
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SceneProto.javaDescriptor.getMessageTypes().get(2)

  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = SceneProto.scalaDescriptor.messages(2)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)

  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)

  lazy val defaultInstance = protocol.scene.JumpInfo(
    positionX = 0.0f,
    positionY = 0.0f,
    highestPosX = 0.0f,
    highestPosY = 0.0f,
    finalPosX = 0.0f,
    finalPosY = 0.0f,
    face = 0.0f
  )

  final class Builder private(
                               private var __positionX: _root_.scala.Float,
                               private var __positionY: _root_.scala.Float,
                               private var __highestPosX: _root_.scala.Float,
                               private var __highestPosY: _root_.scala.Float,
                               private var __finalPosX: _root_.scala.Float,
                               private var __finalPosY: _root_.scala.Float,
                               private var __face: _root_.scala.Float,
                               private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
                             ) extends _root_.scalapb.MessageBuilder[protocol.scene.JumpInfo] {
    private var __requiredFields0: _root_.scala.Long = 0x7fL

    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 13 =>
            __positionX = _input__.readFloat()
            __requiredFields0 &= 0xfffffffffffffffeL
          case 21 =>
            __positionY = _input__.readFloat()
            __requiredFields0 &= 0xfffffffffffffffdL
          case 29 =>
            __highestPosX = _input__.readFloat()
            __requiredFields0 &= 0xfffffffffffffffbL
          case 37 =>
            __highestPosY = _input__.readFloat()
            __requiredFields0 &= 0xfffffffffffffff7L
          case 45 =>
            __finalPosX = _input__.readFloat()
            __requiredFields0 &= 0xffffffffffffffefL
          case 53 =>
            __finalPosY = _input__.readFloat()
            __requiredFields0 &= 0xffffffffffffffdfL
          case 61 =>
            __face = _input__.readFloat()
            __requiredFields0 &= 0xffffffffffffffbfL
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }

    def result(): protocol.scene.JumpInfo = {
      if (__requiredFields0 != 0L) {
        throw new _root_.com.google.protobuf.InvalidProtocolBufferException("Message missing required fields.")
      }
      protocol.scene.JumpInfo(
        positionX = __positionX,
        positionY = __positionY,
        highestPosX = __highestPosX,
        highestPosY = __highestPosY,
        finalPosX = __finalPosX,
        finalPosY = __finalPosY,
        face = __face,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }

  object Builder extends _root_.scalapb.MessageBuilderCompanion[protocol.scene.JumpInfo, protocol.scene.JumpInfo.Builder] {
    def apply(): Builder = new Builder(
      __positionX = 0.0f,
      __positionY = 0.0f,
      __highestPosX = 0.0f,
      __highestPosY = 0.0f,
      __finalPosX = 0.0f,
      __finalPosY = 0.0f,
      __face = 0.0f,
      `_unknownFields__` = null
    )

    def apply(`_message__`: protocol.scene.JumpInfo): Builder = new Builder(
      __positionX = _message__.positionX,
      __positionY = _message__.positionY,
      __highestPosX = _message__.highestPosX,
      __highestPosY = _message__.highestPosY,
      __finalPosX = _message__.finalPosX,
      __finalPosY = _message__.finalPosY,
      __face = _message__.face,
      `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }

  def newBuilder: Builder = protocol.scene.JumpInfo.Builder()

  def newBuilder(`_message__`: protocol.scene.JumpInfo): Builder = protocol.scene.JumpInfo.Builder(_message__)

  implicit class JumpInfoLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, protocol.scene.JumpInfo]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, protocol.scene.JumpInfo](_l) {
    def positionX: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.positionX)((c_, f_) => c_.copy(positionX = f_))

    def positionY: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.positionY)((c_, f_) => c_.copy(positionY = f_))

    def highestPosX: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.highestPosX)((c_, f_) => c_.copy(highestPosX = f_))

    def highestPosY: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.highestPosY)((c_, f_) => c_.copy(highestPosY = f_))

    def finalPosX: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.finalPosX)((c_, f_) => c_.copy(finalPosX = f_))

    def finalPosY: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.finalPosY)((c_, f_) => c_.copy(finalPosY = f_))

    def face: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.face)((c_, f_) => c_.copy(face = f_))
  }

  final val POSITIONX_FIELD_NUMBER = 1
  final val POSITIONY_FIELD_NUMBER = 2
  final val HIGHESTPOSX_FIELD_NUMBER = 3
  final val HIGHESTPOSY_FIELD_NUMBER = 4
  final val FINALPOSX_FIELD_NUMBER = 5
  final val FINALPOSY_FIELD_NUMBER = 6
  final val FACE_FIELD_NUMBER = 7

  def of(
          positionX: _root_.scala.Float,
          positionY: _root_.scala.Float,
          highestPosX: _root_.scala.Float,
          highestPosY: _root_.scala.Float,
          finalPosX: _root_.scala.Float,
          finalPosY: _root_.scala.Float,
          face: _root_.scala.Float
        ): _root_.protocol.scene.JumpInfo = _root_.protocol.scene.JumpInfo(
    positionX,
    positionY,
    highestPosX,
    highestPosY,
    finalPosX,
    finalPosY,
    face
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[protocol.JumpInfo])
}
