// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.scene

object SceneProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      protocol.scene.MoveInfo,
      protocol.scene.StopInfo,
      protocol.scene.JumpInfo,
      protocol.scene.CS10030,
      protocol.scene.SC10030,
      protocol.scene.CS10031,
      protocol.scene.SC10031,
      protocol.scene.CS10032,
      protocol.scene.SC10032,
      protocol.scene.CS10033,
      protocol.scene.SC10033,
      protocol.scene.SC10034,
      protocol.scene.CS10035,
      protocol.scene.SC10035,
      protocol.scene.CS10036,
      protocol.scene.SC10036
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgtzY2VuZS5wcm90bxIIcHJvdG9jb2wiswEKCE1vdmVJbmZvEiwKCXBvc2l0aW9uWBgBIAIoAkIO4j8LEglwb3NpdGlvblhSC
  XBvc2l0aW9uWBIsCglwb3NpdGlvblkYAiACKAJCDuI/CxIJcG9zaXRpb25ZUglwb3NpdGlvblkSHQoEZmFjZRgDIAIoBUIJ4j8GE
  gRmYWNlUgRmYWNlEiwKCWRpcmVjdGlvbhgEIAIoAkIO4j8LEglkaXJlY3Rpb25SCWRpcmVjdGlvbiKFAQoIU3RvcEluZm8SLAoJc
  G9zaXRpb25YGAEgAigCQg7iPwsSCXBvc2l0aW9uWFIJcG9zaXRpb25YEiwKCXBvc2l0aW9uWRgCIAIoAkIO4j8LEglwb3NpdGlvb
  llSCXBvc2l0aW9uWRIdCgRmYWNlGAMgAigFQgniPwYSBGZhY2VSBGZhY2UiyQIKCEp1bXBJbmZvEiwKCXBvc2l0aW9uWBgBIAIoA
  kIO4j8LEglwb3NpdGlvblhSCXBvc2l0aW9uWBIsCglwb3NpdGlvblkYAiACKAJCDuI/CxIJcG9zaXRpb25ZUglwb3NpdGlvblkSM
  goLaGlnaGVzdFBvc1gYAyACKAJCEOI/DRILaGlnaGVzdFBvc1hSC2hpZ2hlc3RQb3NYEjIKC2hpZ2hlc3RQb3NZGAQgAigCQhDiP
  w0SC2hpZ2hlc3RQb3NZUgtoaWdoZXN0UG9zWRIsCglmaW5hbFBvc1gYBSACKAJCDuI/CxIJZmluYWxQb3NYUglmaW5hbFBvc1gSL
  AoJZmluYWxQb3NZGAYgAigCQg7iPwsSCWZpbmFsUG9zWVIJZmluYWxQb3NZEh0KBGZhY2UYByACKAVCCeI/BhIEZmFjZVIEZmFjZ
  SIxCgdDUzEwMDMwEiYKB3NjZW5lSWQYASACKANCDOI/CRIHc2NlbmVJZFIHc2NlbmVJZCKNAQoHU0MxMDAzMBImCgdzY2VuZUlkG
  AEgAigDQgziPwkSB3NjZW5lSWRSB3NjZW5lSWQSLAoJcG9zaXRpb25YGAIgAigCQg7iPwsSCXBvc2l0aW9uWFIJcG9zaXRpb25YE
  iwKCXBvc2l0aW9uWRgDIAIoAkIO4j8LEglwb3NpdGlvbllSCXBvc2l0aW9uWSIxCgdDUzEwMDMxEiYKB3NjZW5lSWQYASACKANCD
  OI/CRIHc2NlbmVJZFIHc2NlbmVJZCI0CgdTQzEwMDMxEikKCHBsYXllcklkGAEgAigDQg3iPwoSCHBsYXllcklkUghwbGF5ZXJJZ
  CJICgdDUzEwMDMyEj0KCG1vdmVJbmZvGAEgAigLMhIucHJvdG9jb2wuTW92ZUluZm9CDeI/ChIIbW92ZUluZm9SCG1vdmVJbmZvI
  nkKB1NDMTAwMzISLwoKb3JnYW5pc21JZBgBIAIoA0IP4j8MEgpvcmdhbmlzbUlkUgpvcmdhbmlzbUlkEj0KCG1vdmVJbmZvGAIgA
  igLMhIucHJvdG9jb2wuTW92ZUluZm9CDeI/ChIIbW92ZUluZm9SCG1vdmVJbmZvIkgKB0NTMTAwMzMSPQoIc3RvcEluZm8YASACK
  AsyEi5wcm90b2NvbC5TdG9wSW5mb0IN4j8KEghzdG9wSW5mb1IIc3RvcEluZm8ieQoHU0MxMDAzMxIvCgpvcmdhbmlzbUlkGAEgA
  igDQg/iPwwSCm9yZ2FuaXNtSWRSCm9yZ2FuaXNtSWQSPQoIc3RvcEluZm8YAiACKAsyEi5wcm90b2NvbC5TdG9wSW5mb0IN4j8KE
  ghzdG9wSW5mb1IIc3RvcEluZm8i7AEKB1NDMTAwMzQSLwoKb3JnYW5pc21JZBgBIAIoA0IP4j8MEgpvcmdhbmlzbUlkUgpvcmdhb
  mlzbUlkEjUKDG9yZ2FuaXNtVHlwZRgCIAIoBUIR4j8OEgxvcmdhbmlzbVR5cGVSDG9yZ2FuaXNtVHlwZRIsCglwb3NpdGlvblgYA
  yACKAJCDuI/CxIJcG9zaXRpb25YUglwb3NpdGlvblgSLAoJcG9zaXRpb25ZGAQgAigCQg7iPwsSCXBvc2l0aW9uWVIJcG9zaXRpb
  25ZEh0KBGZhY2UYBSACKAVCCeI/BhIEZmFjZVIEZmFjZSJICgdDUzEwMDM1Ej0KCGp1bXBJbmZvGAEgAigLMhIucHJvdG9jb2wuS
  nVtcEluZm9CDeI/ChIIanVtcEluZm9SCGp1bXBJbmZvInkKB1NDMTAwMzUSLwoKb3JnYW5pc21JZBgBIAIoA0IP4j8MEgpvcmdhb
  mlzbUlkUgpvcmdhbmlzbUlkEj0KCGp1bXBJbmZvGAIgAigLMhIucHJvdG9jb2wuSnVtcEluZm9CDeI/ChIIanVtcEluZm9SCGp1b
  XBJbmZvIpYBCgdDUzEwMDM2EiwKCXBvc2l0aW9uWBgBIAIoAkIO4j8LEglwb3NpdGlvblhSCXBvc2l0aW9uWBIsCglwb3NpdGlvb
  lkYAiACKAJCDuI/CxIJcG9zaXRpb25ZUglwb3NpdGlvblkSLwoKb3JnYW5pc21JZBgDIAIoA0IP4j8MEgpvcmdhbmlzbUlkUgpvc
  mdhbmlzbUlkIpYBCgdTQzEwMDM2EiwKCXBvc2l0aW9uWBgBIAIoAkIO4j8LEglwb3NpdGlvblhSCXBvc2l0aW9uWBIsCglwb3Npd
  GlvblkYAiACKAJCDuI/CxIJcG9zaXRpb25ZUglwb3NpdGlvblkSLwoKb3JnYW5pc21JZBgDIAIoA0IP4j8MEgpvcmdhbmlzbUlkU
  gpvcmdhbmlzbUlk"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor =
    protocol.Scene.getDescriptor()
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}