// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.equip
import _root_.scalapb.internal.compat.JavaConverters._

/** 请求卸下装备
  *
  * @param slots
  *   装备部位列表
  */
@SerialVersionUID(0L)
final case class CS11102(
    slots: _root_.scala.Seq[_root_.scala.Int] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[CS11102] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      slots.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(1, __value)
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      slots.foreach { __v =>
        val __m = __v
        _output__.writeInt32(1, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def clearSlots = copy(slots = _root_.scala.Seq.empty)
    def addSlots(__vs: _root_.scala.Int*): CS11102 = addAllSlots(__vs)
    def addAllSlots(__vs: Iterable[_root_.scala.Int]): CS11102 = copy(slots = slots ++ __vs)
    def withSlots(__v: _root_.scala.Seq[_root_.scala.Int]): CS11102 = copy(slots = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => slots
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(slots.iterator.map(_root_.scalapb.descriptors.PInt(_)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = protocol.equip.CS11102
    // @@protoc_insertion_point(GeneratedMessage[protocol.CS11102])
}

object CS11102 extends scalapb.GeneratedMessageCompanion[protocol.equip.CS11102] with scalapb.HasBuilder[protocol.equip.CS11102] with scalapb.JavaProtoSupport[protocol.equip.CS11102, protocol.Equip.CS11102] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[protocol.equip.CS11102] with scalapb.HasBuilder[protocol.equip.CS11102] with scalapb.JavaProtoSupport[protocol.equip.CS11102, protocol.Equip.CS11102] = this
  def toJavaProto(scalaPbSource: protocol.equip.CS11102): protocol.Equip.CS11102 = {
    val javaPbOut = protocol.Equip.CS11102.newBuilder
    javaPbOut.addAllSlots(_root_.scalapb.internal.compat.toIterable(scalaPbSource.slots.iterator.map(_root_.scala.Int.box(_))).asJava)
    javaPbOut.build
  }
  def fromJavaProto(javaPbSource: protocol.Equip.CS11102): protocol.equip.CS11102 = protocol.equip.CS11102(
    slots = javaPbSource.getSlotsList.asScala.iterator.map(_.intValue).toSeq
  )
  def merge(`_message__`: protocol.equip.CS11102, `_input__`: _root_.com.google.protobuf.CodedInputStream): protocol.equip.CS11102 = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[protocol.equip.CS11102] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      protocol.equip.CS11102(
        slots = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[_root_.scala.Int]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = EquipProto.javaDescriptor.getMessageTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = EquipProto.scalaDescriptor.messages(5)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = protocol.equip.CS11102(
    slots = _root_.scala.Seq.empty
  )
  final class Builder private (
    private val __slots: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Int],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[protocol.equip.CS11102] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __slots += _input__.readInt32()
          case 10 => {
            val length = _input__.readRawVarint32()
            val oldLimit = _input__.pushLimit(length)
            while (_input__.getBytesUntilLimit > 0) {
              __slots += _input__.readInt32()
            }
            _input__.popLimit(oldLimit)
          }
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): protocol.equip.CS11102 = {
      protocol.equip.CS11102(
        slots = __slots.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[protocol.equip.CS11102, protocol.equip.CS11102.Builder] {
    def apply(): Builder = new Builder(
      __slots = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Int],
      `_unknownFields__` = null
    )
    def apply(`_message__`: protocol.equip.CS11102): Builder = new Builder(
        __slots = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Int] ++= _message__.slots,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = protocol.equip.CS11102.Builder()
  def newBuilder(`_message__`: protocol.equip.CS11102): Builder = protocol.equip.CS11102.Builder(_message__)
  implicit class CS11102Lens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, protocol.equip.CS11102]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, protocol.equip.CS11102](_l) {
    def slots: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Int]] = field(_.slots)((c_, f_) => c_.copy(slots = f_))
  }
  final val SLOTS_FIELD_NUMBER = 1
  def of(
    slots: _root_.scala.Seq[_root_.scala.Int]
  ): _root_.protocol.equip.CS11102 = _root_.protocol.equip.CS11102(
    slots
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[protocol.CS11102])
}
