// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.p1

/** delete one personalAccount
  */
@SerialVersionUID(0L)
final case class cs6(
    infoId: _root_.scala.Long,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[cs6] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = infoId
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      
      {
        val __v = infoId
        _output__.writeInt64(1, __v)
      };
      unknownFields.writeTo(_output__)
    }
    def withInfoId(__v: _root_.scala.Long): cs6 = copy(infoId = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => infoId
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(infoId)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = protocol.p1.cs6
    // @@protoc_insertion_point(GeneratedMessage[protocol.cs6])
}

object cs6 extends scalapb.GeneratedMessageCompanion[protocol.p1.cs6] with scalapb.HasBuilder[protocol.p1.cs6] with scalapb.JavaProtoSupport[protocol.p1.cs6, protocol.P1.cs6] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[protocol.p1.cs6] with scalapb.HasBuilder[protocol.p1.cs6] with scalapb.JavaProtoSupport[protocol.p1.cs6, protocol.P1.cs6] = this
  def toJavaProto(scalaPbSource: protocol.p1.cs6): protocol.P1.cs6 = {
    val javaPbOut = protocol.P1.cs6.newBuilder
    javaPbOut.setInfoId(scalaPbSource.infoId)
    javaPbOut.build
  }
  def fromJavaProto(javaPbSource: protocol.P1.cs6): protocol.p1.cs6 = protocol.p1.cs6(
    infoId = javaPbSource.getInfoId.longValue
  )
  def merge(`_message__`: protocol.p1.cs6, `_input__`: _root_.com.google.protobuf.CodedInputStream): protocol.p1.cs6 = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[protocol.p1.cs6] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      protocol.p1.cs6(
        infoId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).get.as[_root_.scala.Long]
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = P1Proto.javaDescriptor.getMessageTypes().get(10)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = P1Proto.scalaDescriptor.messages(10)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = protocol.p1.cs6(
    infoId = 0L
  )
  final class Builder private (
    private var __infoId: _root_.scala.Long,
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[protocol.p1.cs6] {
    private var __requiredFields0: _root_.scala.Long = 0x1L
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __infoId = _input__.readInt64()
            __requiredFields0 &= 0xfffffffffffffffeL
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): protocol.p1.cs6 = {
      if (__requiredFields0 != 0L) { throw new _root_.com.google.protobuf.InvalidProtocolBufferException("Message missing required fields.") } 
      protocol.p1.cs6(
        infoId = __infoId,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[protocol.p1.cs6, protocol.p1.cs6.Builder] {
    def apply(): Builder = new Builder(
      __infoId = 0L,
      `_unknownFields__` = null
    )
    def apply(`_message__`: protocol.p1.cs6): Builder = new Builder(
        __infoId = _message__.infoId,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = protocol.p1.cs6.Builder()
  def newBuilder(`_message__`: protocol.p1.cs6): Builder = protocol.p1.cs6.Builder(_message__)
  implicit class cs6Lens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, protocol.p1.cs6]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, protocol.p1.cs6](_l) {
    def infoId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.infoId)((c_, f_) => c_.copy(infoId = f_))
  }
  final val INFOID_FIELD_NUMBER = 1
  def of(
    infoId: _root_.scala.Long
  ): _root_.protocol.p1.cs6 = _root_.protocol.p1.cs6(
    infoId
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[protocol.cs6])
}
