// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package protocol.p1

object P1Proto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    protocol.base.BaseProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      protocol.p1.cs1,
      protocol.p1.sc1,
      protocol.p1.cs2,
      protocol.p1.sc2,
      protocol.p1.cs3,
      protocol.p1.sc3,
      protocol.p1.cs4,
      protocol.p1.sc4
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CghwMS5wcm90bxIIcHJvdG9jb2waCmJhc2UucHJvdG8iYwoDY3MxEj0KB2FjY291bnQYASACKAsyFS5wcm90b2NvbC5BY2Nvd
  W50SW5mb0IM4j8JEgdhY2NvdW50UgdhY2NvdW50Eh0KBG5hbWUYAiACKAlCCeI/BhIEbmFtZVIEbmFtZSItCgNzYzESJgoHc3VjY
  2VzcxgBIAIoCEIM4j8JEgdzdWNjZXNzUgdzdWNjZXNzIkQKA2NzMhI9CgdhY2NvdW50GAEgAigLMhUucHJvdG9jb2wuQWNjb3Vud
  EluZm9CDOI/CRIHYWNjb3VudFIHYWNjb3VudCJSCgNzYzISJgoHc3VjY2VzcxgBIAIoCEIM4j8JEgdzdWNjZXNzUgdzdWNjZXNzE
  iMKBnVzZXJJZBgCIAIoA0IL4j8IEgZ1c2VySWRSBnVzZXJJZCIqCgNjczMSIwoGcmVhc29uGAEgAigFQgviPwgSBnJlYXNvblIGc
  mVhc29uIioKA3NjMxIjCgZyZWFzb24YASACKAVCC+I/CBIGcmVhc29uUgZyZWFzb24iRAoDY3M0Ej0KB2FjY291bnQYASACKAsyF
  S5wcm90b2NvbC5BY2NvdW50SW5mb0IM4j8JEgdhY2NvdW50UgdhY2NvdW50IlIKA3NjNBImCgdzdWNjZXNzGAEgAigIQgziPwkSB
  3N1Y2Nlc3NSB3N1Y2Nlc3MSIwoGdXNlcklkGAIgAigDQgviPwgSBnVzZXJJZFIGdXNlcklk"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor =
    protocol.P1.getDescriptor()
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}