// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attribute.proto

package protocol;

public final class Attribute {
  private Attribute() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CS10040OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.CS10040)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *请求战斗数值
   * </pre>
   *
   * Protobuf type {@code protocol.CS10040}
   */
  public  static final class CS10040 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.CS10040)
      CS10040OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CS10040.newBuilder() to construct.
    private CS10040(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS10040() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CS10040();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CS10040(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Attribute.internal_static_protocol_CS10040_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Attribute.internal_static_protocol_CS10040_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Attribute.CS10040.class, protocol.Attribute.CS10040.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Attribute.CS10040)) {
        return super.equals(obj);
      }
      protocol.Attribute.CS10040 other = (protocol.Attribute.CS10040) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Attribute.CS10040 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.CS10040 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.CS10040 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.CS10040 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.CS10040 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.CS10040 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.CS10040 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Attribute.CS10040 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Attribute.CS10040 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Attribute.CS10040 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Attribute.CS10040 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Attribute.CS10040 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Attribute.CS10040 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求战斗数值
     * </pre>
     *
     * Protobuf type {@code protocol.CS10040}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.CS10040)
        protocol.Attribute.CS10040OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Attribute.internal_static_protocol_CS10040_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Attribute.internal_static_protocol_CS10040_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Attribute.CS10040.class, protocol.Attribute.CS10040.Builder.class);
      }

      // Construct using protocol.Attribute.CS10040.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Attribute.internal_static_protocol_CS10040_descriptor;
      }

      @java.lang.Override
      public protocol.Attribute.CS10040 getDefaultInstanceForType() {
        return protocol.Attribute.CS10040.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Attribute.CS10040 build() {
        protocol.Attribute.CS10040 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Attribute.CS10040 buildPartial() {
        protocol.Attribute.CS10040 result = new protocol.Attribute.CS10040(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Attribute.CS10040) {
          return mergeFrom((protocol.Attribute.CS10040)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Attribute.CS10040 other) {
        if (other == protocol.Attribute.CS10040.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Attribute.CS10040 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Attribute.CS10040) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.CS10040)
    }

    // @@protoc_insertion_point(class_scope:protocol.CS10040)
    private static final protocol.Attribute.CS10040 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Attribute.CS10040();
    }

    public static protocol.Attribute.CS10040 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CS10040>
        PARSER = new com.google.protobuf.AbstractParser<CS10040>() {
      @java.lang.Override
      public CS10040 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CS10040(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS10040> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS10040> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Attribute.CS10040 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC10040OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.SC10040)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 fightOrganismId = 1;</code>
     * @return Whether the fightOrganismId field is set.
     */
    boolean hasFightOrganismId();
    /**
     * <code>required int64 fightOrganismId = 1;</code>
     * @return The fightOrganismId.
     */
    long getFightOrganismId();

    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    java.util.List<protocol.Base.AttributeMap> 
        getAttributeMapList();
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    protocol.Base.AttributeMap getAttributeMap(int index);
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    int getAttributeMapCount();
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    java.util.List<? extends protocol.Base.AttributeMapOrBuilder> 
        getAttributeMapOrBuilderList();
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    protocol.Base.AttributeMapOrBuilder getAttributeMapOrBuilder(
        int index);
  }
  /**
   * <pre>
   *返回战斗数值
   * </pre>
   *
   * Protobuf type {@code protocol.SC10040}
   */
  public  static final class SC10040 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.SC10040)
      SC10040OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC10040.newBuilder() to construct.
    private SC10040(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC10040() {
      attributeMap_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SC10040();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC10040(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              fightOrganismId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                attributeMap_ = new java.util.ArrayList<protocol.Base.AttributeMap>();
                mutable_bitField0_ |= 0x00000002;
              }
              attributeMap_.add(
                  input.readMessage(protocol.Base.AttributeMap.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          attributeMap_ = java.util.Collections.unmodifiableList(attributeMap_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Attribute.internal_static_protocol_SC10040_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Attribute.internal_static_protocol_SC10040_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Attribute.SC10040.class, protocol.Attribute.SC10040.Builder.class);
    }

    private int bitField0_;
    public static final int FIGHTORGANISMID_FIELD_NUMBER = 1;
    private long fightOrganismId_;
    /**
     * <code>required int64 fightOrganismId = 1;</code>
     * @return Whether the fightOrganismId field is set.
     */
    public boolean hasFightOrganismId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 fightOrganismId = 1;</code>
     * @return The fightOrganismId.
     */
    public long getFightOrganismId() {
      return fightOrganismId_;
    }

    public static final int ATTRIBUTEMAP_FIELD_NUMBER = 2;
    private java.util.List<protocol.Base.AttributeMap> attributeMap_;
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    public java.util.List<protocol.Base.AttributeMap> getAttributeMapList() {
      return attributeMap_;
    }
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    public java.util.List<? extends protocol.Base.AttributeMapOrBuilder> 
        getAttributeMapOrBuilderList() {
      return attributeMap_;
    }
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    public int getAttributeMapCount() {
      return attributeMap_.size();
    }
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    public protocol.Base.AttributeMap getAttributeMap(int index) {
      return attributeMap_.get(index);
    }
    /**
     * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
     */
    public protocol.Base.AttributeMapOrBuilder getAttributeMapOrBuilder(
        int index) {
      return attributeMap_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFightOrganismId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAttributeMapCount(); i++) {
        if (!getAttributeMap(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, fightOrganismId_);
      }
      for (int i = 0; i < attributeMap_.size(); i++) {
        output.writeMessage(2, attributeMap_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, fightOrganismId_);
      }
      for (int i = 0; i < attributeMap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, attributeMap_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Attribute.SC10040)) {
        return super.equals(obj);
      }
      protocol.Attribute.SC10040 other = (protocol.Attribute.SC10040) obj;

      if (hasFightOrganismId() != other.hasFightOrganismId()) return false;
      if (hasFightOrganismId()) {
        if (getFightOrganismId()
            != other.getFightOrganismId()) return false;
      }
      if (!getAttributeMapList()
          .equals(other.getAttributeMapList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFightOrganismId()) {
        hash = (37 * hash) + FIGHTORGANISMID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFightOrganismId());
      }
      if (getAttributeMapCount() > 0) {
        hash = (37 * hash) + ATTRIBUTEMAP_FIELD_NUMBER;
        hash = (53 * hash) + getAttributeMapList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Attribute.SC10040 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.SC10040 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.SC10040 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.SC10040 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.SC10040 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.SC10040 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.SC10040 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Attribute.SC10040 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Attribute.SC10040 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Attribute.SC10040 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Attribute.SC10040 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Attribute.SC10040 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Attribute.SC10040 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *返回战斗数值
     * </pre>
     *
     * Protobuf type {@code protocol.SC10040}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.SC10040)
        protocol.Attribute.SC10040OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Attribute.internal_static_protocol_SC10040_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Attribute.internal_static_protocol_SC10040_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Attribute.SC10040.class, protocol.Attribute.SC10040.Builder.class);
      }

      // Construct using protocol.Attribute.SC10040.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAttributeMapFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fightOrganismId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (attributeMapBuilder_ == null) {
          attributeMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          attributeMapBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Attribute.internal_static_protocol_SC10040_descriptor;
      }

      @java.lang.Override
      public protocol.Attribute.SC10040 getDefaultInstanceForType() {
        return protocol.Attribute.SC10040.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Attribute.SC10040 build() {
        protocol.Attribute.SC10040 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Attribute.SC10040 buildPartial() {
        protocol.Attribute.SC10040 result = new protocol.Attribute.SC10040(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fightOrganismId_ = fightOrganismId_;
          to_bitField0_ |= 0x00000001;
        }
        if (attributeMapBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            attributeMap_ = java.util.Collections.unmodifiableList(attributeMap_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.attributeMap_ = attributeMap_;
        } else {
          result.attributeMap_ = attributeMapBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Attribute.SC10040) {
          return mergeFrom((protocol.Attribute.SC10040)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Attribute.SC10040 other) {
        if (other == protocol.Attribute.SC10040.getDefaultInstance()) return this;
        if (other.hasFightOrganismId()) {
          setFightOrganismId(other.getFightOrganismId());
        }
        if (attributeMapBuilder_ == null) {
          if (!other.attributeMap_.isEmpty()) {
            if (attributeMap_.isEmpty()) {
              attributeMap_ = other.attributeMap_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAttributeMapIsMutable();
              attributeMap_.addAll(other.attributeMap_);
            }
            onChanged();
          }
        } else {
          if (!other.attributeMap_.isEmpty()) {
            if (attributeMapBuilder_.isEmpty()) {
              attributeMapBuilder_.dispose();
              attributeMapBuilder_ = null;
              attributeMap_ = other.attributeMap_;
              bitField0_ = (bitField0_ & ~0x00000002);
              attributeMapBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAttributeMapFieldBuilder() : null;
            } else {
              attributeMapBuilder_.addAllMessages(other.attributeMap_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFightOrganismId()) {
          return false;
        }
        for (int i = 0; i < getAttributeMapCount(); i++) {
          if (!getAttributeMap(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Attribute.SC10040 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Attribute.SC10040) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long fightOrganismId_ ;
      /**
       * <code>required int64 fightOrganismId = 1;</code>
       * @return Whether the fightOrganismId field is set.
       */
      public boolean hasFightOrganismId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 fightOrganismId = 1;</code>
       * @return The fightOrganismId.
       */
      public long getFightOrganismId() {
        return fightOrganismId_;
      }
      /**
       * <code>required int64 fightOrganismId = 1;</code>
       * @param value The fightOrganismId to set.
       * @return This builder for chaining.
       */
      public Builder setFightOrganismId(long value) {
        bitField0_ |= 0x00000001;
        fightOrganismId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fightOrganismId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFightOrganismId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fightOrganismId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<protocol.Base.AttributeMap> attributeMap_ =
        java.util.Collections.emptyList();
      private void ensureAttributeMapIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          attributeMap_ = new java.util.ArrayList<protocol.Base.AttributeMap>(attributeMap_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Base.AttributeMap, protocol.Base.AttributeMap.Builder, protocol.Base.AttributeMapOrBuilder> attributeMapBuilder_;

      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public java.util.List<protocol.Base.AttributeMap> getAttributeMapList() {
        if (attributeMapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributeMap_);
        } else {
          return attributeMapBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public int getAttributeMapCount() {
        if (attributeMapBuilder_ == null) {
          return attributeMap_.size();
        } else {
          return attributeMapBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public protocol.Base.AttributeMap getAttributeMap(int index) {
        if (attributeMapBuilder_ == null) {
          return attributeMap_.get(index);
        } else {
          return attributeMapBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder setAttributeMap(
          int index, protocol.Base.AttributeMap value) {
        if (attributeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeMapIsMutable();
          attributeMap_.set(index, value);
          onChanged();
        } else {
          attributeMapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder setAttributeMap(
          int index, protocol.Base.AttributeMap.Builder builderForValue) {
        if (attributeMapBuilder_ == null) {
          ensureAttributeMapIsMutable();
          attributeMap_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributeMapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder addAttributeMap(protocol.Base.AttributeMap value) {
        if (attributeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeMapIsMutable();
          attributeMap_.add(value);
          onChanged();
        } else {
          attributeMapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder addAttributeMap(
          int index, protocol.Base.AttributeMap value) {
        if (attributeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeMapIsMutable();
          attributeMap_.add(index, value);
          onChanged();
        } else {
          attributeMapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder addAttributeMap(
          protocol.Base.AttributeMap.Builder builderForValue) {
        if (attributeMapBuilder_ == null) {
          ensureAttributeMapIsMutable();
          attributeMap_.add(builderForValue.build());
          onChanged();
        } else {
          attributeMapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder addAttributeMap(
          int index, protocol.Base.AttributeMap.Builder builderForValue) {
        if (attributeMapBuilder_ == null) {
          ensureAttributeMapIsMutable();
          attributeMap_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributeMapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder addAllAttributeMap(
          java.lang.Iterable<? extends protocol.Base.AttributeMap> values) {
        if (attributeMapBuilder_ == null) {
          ensureAttributeMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributeMap_);
          onChanged();
        } else {
          attributeMapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder clearAttributeMap() {
        if (attributeMapBuilder_ == null) {
          attributeMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          attributeMapBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public Builder removeAttributeMap(int index) {
        if (attributeMapBuilder_ == null) {
          ensureAttributeMapIsMutable();
          attributeMap_.remove(index);
          onChanged();
        } else {
          attributeMapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public protocol.Base.AttributeMap.Builder getAttributeMapBuilder(
          int index) {
        return getAttributeMapFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public protocol.Base.AttributeMapOrBuilder getAttributeMapOrBuilder(
          int index) {
        if (attributeMapBuilder_ == null) {
          return attributeMap_.get(index);  } else {
          return attributeMapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public java.util.List<? extends protocol.Base.AttributeMapOrBuilder> 
           getAttributeMapOrBuilderList() {
        if (attributeMapBuilder_ != null) {
          return attributeMapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributeMap_);
        }
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public protocol.Base.AttributeMap.Builder addAttributeMapBuilder() {
        return getAttributeMapFieldBuilder().addBuilder(
            protocol.Base.AttributeMap.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public protocol.Base.AttributeMap.Builder addAttributeMapBuilder(
          int index) {
        return getAttributeMapFieldBuilder().addBuilder(
            index, protocol.Base.AttributeMap.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.AttributeMap attributeMap = 2;</code>
       */
      public java.util.List<protocol.Base.AttributeMap.Builder> 
           getAttributeMapBuilderList() {
        return getAttributeMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Base.AttributeMap, protocol.Base.AttributeMap.Builder, protocol.Base.AttributeMapOrBuilder> 
          getAttributeMapFieldBuilder() {
        if (attributeMapBuilder_ == null) {
          attributeMapBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.Base.AttributeMap, protocol.Base.AttributeMap.Builder, protocol.Base.AttributeMapOrBuilder>(
                  attributeMap_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          attributeMap_ = null;
        }
        return attributeMapBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.SC10040)
    }

    // @@protoc_insertion_point(class_scope:protocol.SC10040)
    private static final protocol.Attribute.SC10040 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Attribute.SC10040();
    }

    public static protocol.Attribute.SC10040 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SC10040>
        PARSER = new com.google.protobuf.AbstractParser<SC10040>() {
      @java.lang.Override
      public SC10040 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC10040(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC10040> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC10040> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Attribute.SC10040 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC10041OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.SC10041)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 fightOrganismId = 1;</code>
     * @return Whether the fightOrganismId field is set.
     */
    boolean hasFightOrganismId();
    /**
     * <code>required int64 fightOrganismId = 1;</code>
     * @return The fightOrganismId.
     */
    long getFightOrganismId();

    /**
     * <pre>
     *战力
     * </pre>
     *
     * <code>required int64 fighting = 2;</code>
     * @return Whether the fighting field is set.
     */
    boolean hasFighting();
    /**
     * <pre>
     *战力
     * </pre>
     *
     * <code>required int64 fighting = 2;</code>
     * @return The fighting.
     */
    long getFighting();
  }
  /**
   * <pre>
   *返回战力
   * </pre>
   *
   * Protobuf type {@code protocol.SC10041}
   */
  public  static final class SC10041 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.SC10041)
      SC10041OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC10041.newBuilder() to construct.
    private SC10041(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC10041() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SC10041();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC10041(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              fightOrganismId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fighting_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Attribute.internal_static_protocol_SC10041_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Attribute.internal_static_protocol_SC10041_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Attribute.SC10041.class, protocol.Attribute.SC10041.Builder.class);
    }

    private int bitField0_;
    public static final int FIGHTORGANISMID_FIELD_NUMBER = 1;
    private long fightOrganismId_;
    /**
     * <code>required int64 fightOrganismId = 1;</code>
     * @return Whether the fightOrganismId field is set.
     */
    public boolean hasFightOrganismId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 fightOrganismId = 1;</code>
     * @return The fightOrganismId.
     */
    public long getFightOrganismId() {
      return fightOrganismId_;
    }

    public static final int FIGHTING_FIELD_NUMBER = 2;
    private long fighting_;
    /**
     * <pre>
     *战力
     * </pre>
     *
     * <code>required int64 fighting = 2;</code>
     * @return Whether the fighting field is set.
     */
    public boolean hasFighting() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *战力
     * </pre>
     *
     * <code>required int64 fighting = 2;</code>
     * @return The fighting.
     */
    public long getFighting() {
      return fighting_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFightOrganismId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFighting()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, fightOrganismId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, fighting_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, fightOrganismId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fighting_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Attribute.SC10041)) {
        return super.equals(obj);
      }
      protocol.Attribute.SC10041 other = (protocol.Attribute.SC10041) obj;

      if (hasFightOrganismId() != other.hasFightOrganismId()) return false;
      if (hasFightOrganismId()) {
        if (getFightOrganismId()
            != other.getFightOrganismId()) return false;
      }
      if (hasFighting() != other.hasFighting()) return false;
      if (hasFighting()) {
        if (getFighting()
            != other.getFighting()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFightOrganismId()) {
        hash = (37 * hash) + FIGHTORGANISMID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFightOrganismId());
      }
      if (hasFighting()) {
        hash = (37 * hash) + FIGHTING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFighting());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Attribute.SC10041 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.SC10041 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.SC10041 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.SC10041 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.SC10041 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Attribute.SC10041 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Attribute.SC10041 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Attribute.SC10041 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Attribute.SC10041 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Attribute.SC10041 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Attribute.SC10041 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Attribute.SC10041 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Attribute.SC10041 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *返回战力
     * </pre>
     *
     * Protobuf type {@code protocol.SC10041}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.SC10041)
        protocol.Attribute.SC10041OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Attribute.internal_static_protocol_SC10041_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Attribute.internal_static_protocol_SC10041_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Attribute.SC10041.class, protocol.Attribute.SC10041.Builder.class);
      }

      // Construct using protocol.Attribute.SC10041.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fightOrganismId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        fighting_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Attribute.internal_static_protocol_SC10041_descriptor;
      }

      @java.lang.Override
      public protocol.Attribute.SC10041 getDefaultInstanceForType() {
        return protocol.Attribute.SC10041.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Attribute.SC10041 build() {
        protocol.Attribute.SC10041 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Attribute.SC10041 buildPartial() {
        protocol.Attribute.SC10041 result = new protocol.Attribute.SC10041(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fightOrganismId_ = fightOrganismId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fighting_ = fighting_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Attribute.SC10041) {
          return mergeFrom((protocol.Attribute.SC10041)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Attribute.SC10041 other) {
        if (other == protocol.Attribute.SC10041.getDefaultInstance()) return this;
        if (other.hasFightOrganismId()) {
          setFightOrganismId(other.getFightOrganismId());
        }
        if (other.hasFighting()) {
          setFighting(other.getFighting());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFightOrganismId()) {
          return false;
        }
        if (!hasFighting()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Attribute.SC10041 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Attribute.SC10041) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long fightOrganismId_ ;
      /**
       * <code>required int64 fightOrganismId = 1;</code>
       * @return Whether the fightOrganismId field is set.
       */
      public boolean hasFightOrganismId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 fightOrganismId = 1;</code>
       * @return The fightOrganismId.
       */
      public long getFightOrganismId() {
        return fightOrganismId_;
      }
      /**
       * <code>required int64 fightOrganismId = 1;</code>
       * @param value The fightOrganismId to set.
       * @return This builder for chaining.
       */
      public Builder setFightOrganismId(long value) {
        bitField0_ |= 0x00000001;
        fightOrganismId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fightOrganismId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFightOrganismId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fightOrganismId_ = 0L;
        onChanged();
        return this;
      }

      private long fighting_ ;
      /**
       * <pre>
       *战力
       * </pre>
       *
       * <code>required int64 fighting = 2;</code>
       * @return Whether the fighting field is set.
       */
      public boolean hasFighting() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *战力
       * </pre>
       *
       * <code>required int64 fighting = 2;</code>
       * @return The fighting.
       */
      public long getFighting() {
        return fighting_;
      }
      /**
       * <pre>
       *战力
       * </pre>
       *
       * <code>required int64 fighting = 2;</code>
       * @param value The fighting to set.
       * @return This builder for chaining.
       */
      public Builder setFighting(long value) {
        bitField0_ |= 0x00000002;
        fighting_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *战力
       * </pre>
       *
       * <code>required int64 fighting = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFighting() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fighting_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.SC10041)
    }

    // @@protoc_insertion_point(class_scope:protocol.SC10041)
    private static final protocol.Attribute.SC10041 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Attribute.SC10041();
    }

    public static protocol.Attribute.SC10041 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SC10041>
        PARSER = new com.google.protobuf.AbstractParser<SC10041>() {
      @java.lang.Override
      public SC10041 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC10041(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC10041> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC10041> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Attribute.SC10041 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CS10040_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CS10040_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SC10040_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SC10040_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SC10041_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SC10041_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017attribute.proto\022\010protocol\032\nbase.proto\"" +
      "\t\n\007CS10040\"P\n\007SC10040\022\027\n\017fightOrganismId" +
      "\030\001 \002(\003\022,\n\014attributeMap\030\002 \003(\0132\026.protocol." +
      "AttributeMap\"4\n\007SC10041\022\027\n\017fightOrganism" +
      "Id\030\001 \002(\003\022\020\n\010fighting\030\002 \002(\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Base.getDescriptor(),
        });
    internal_static_protocol_CS10040_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_CS10040_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CS10040_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_SC10040_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_SC10040_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SC10040_descriptor,
        new java.lang.String[] { "FightOrganismId", "AttributeMap", });
    internal_static_protocol_SC10041_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_SC10041_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SC10041_descriptor,
        new java.lang.String[] { "FightOrganismId", "Fighting", });
    protocol.Base.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
