// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package protocol;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SC10080OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.SC10080)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 applicationErrorId = 1;</code>
     * @return Whether the applicationErrorId field is set.
     */
    boolean hasApplicationErrorId();
    /**
     * <code>required int32 applicationErrorId = 1;</code>
     * @return The applicationErrorId.
     */
    int getApplicationErrorId();
  }
  /**
   * <pre>
   *返回错误码
   * </pre>
   *
   * Protobuf type {@code protocol.SC10080}
   */
  public  static final class SC10080 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.SC10080)
      SC10080OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC10080.newBuilder() to construct.
    private SC10080(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC10080() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SC10080();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC10080(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              applicationErrorId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Common.internal_static_protocol_SC10080_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Common.internal_static_protocol_SC10080_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Common.SC10080.class, protocol.Common.SC10080.Builder.class);
    }

    private int bitField0_;
    public static final int APPLICATIONERRORID_FIELD_NUMBER = 1;
    private int applicationErrorId_;
    /**
     * <code>required int32 applicationErrorId = 1;</code>
     * @return Whether the applicationErrorId field is set.
     */
    public boolean hasApplicationErrorId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 applicationErrorId = 1;</code>
     * @return The applicationErrorId.
     */
    public int getApplicationErrorId() {
      return applicationErrorId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasApplicationErrorId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, applicationErrorId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, applicationErrorId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Common.SC10080)) {
        return super.equals(obj);
      }
      protocol.Common.SC10080 other = (protocol.Common.SC10080) obj;

      if (hasApplicationErrorId() != other.hasApplicationErrorId()) return false;
      if (hasApplicationErrorId()) {
        if (getApplicationErrorId()
            != other.getApplicationErrorId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasApplicationErrorId()) {
        hash = (37 * hash) + APPLICATIONERRORID_FIELD_NUMBER;
        hash = (53 * hash) + getApplicationErrorId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Common.SC10080 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10080 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10080 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10080 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10080 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10080 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10080 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10080 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.SC10080 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10080 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.SC10080 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10080 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Common.SC10080 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *返回错误码
     * </pre>
     *
     * Protobuf type {@code protocol.SC10080}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.SC10080)
        protocol.Common.SC10080OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Common.internal_static_protocol_SC10080_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Common.internal_static_protocol_SC10080_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Common.SC10080.class, protocol.Common.SC10080.Builder.class);
      }

      // Construct using protocol.Common.SC10080.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        applicationErrorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Common.internal_static_protocol_SC10080_descriptor;
      }

      @java.lang.Override
      public protocol.Common.SC10080 getDefaultInstanceForType() {
        return protocol.Common.SC10080.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Common.SC10080 build() {
        protocol.Common.SC10080 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Common.SC10080 buildPartial() {
        protocol.Common.SC10080 result = new protocol.Common.SC10080(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.applicationErrorId_ = applicationErrorId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Common.SC10080) {
          return mergeFrom((protocol.Common.SC10080)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Common.SC10080 other) {
        if (other == protocol.Common.SC10080.getDefaultInstance()) return this;
        if (other.hasApplicationErrorId()) {
          setApplicationErrorId(other.getApplicationErrorId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasApplicationErrorId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Common.SC10080 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Common.SC10080) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int applicationErrorId_ ;
      /**
       * <code>required int32 applicationErrorId = 1;</code>
       * @return Whether the applicationErrorId field is set.
       */
      public boolean hasApplicationErrorId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 applicationErrorId = 1;</code>
       * @return The applicationErrorId.
       */
      public int getApplicationErrorId() {
        return applicationErrorId_;
      }
      /**
       * <code>required int32 applicationErrorId = 1;</code>
       * @param value The applicationErrorId to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationErrorId(int value) {
        bitField0_ |= 0x00000001;
        applicationErrorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 applicationErrorId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationErrorId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        applicationErrorId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.SC10080)
    }

    // @@protoc_insertion_point(class_scope:protocol.SC10080)
    private static final protocol.Common.SC10080 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Common.SC10080();
    }

    public static protocol.Common.SC10080 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SC10080>
        PARSER = new com.google.protobuf.AbstractParser<SC10080>() {
      @java.lang.Override
      public SC10080 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC10080(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC10080> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC10080> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Common.SC10080 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CS10081OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.CS10081)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *请求服务器时间
   * </pre>
   *
   * Protobuf type {@code protocol.CS10081}
   */
  public  static final class CS10081 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.CS10081)
      CS10081OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CS10081.newBuilder() to construct.
    private CS10081(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS10081() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CS10081();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CS10081(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Common.internal_static_protocol_CS10081_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Common.internal_static_protocol_CS10081_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Common.CS10081.class, protocol.Common.CS10081.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Common.CS10081)) {
        return super.equals(obj);
      }
      protocol.Common.CS10081 other = (protocol.Common.CS10081) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Common.CS10081 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.CS10081 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.CS10081 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.CS10081 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.CS10081 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.CS10081 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.CS10081 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.CS10081 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.CS10081 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Common.CS10081 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.CS10081 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.CS10081 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Common.CS10081 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求服务器时间
     * </pre>
     *
     * Protobuf type {@code protocol.CS10081}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.CS10081)
        protocol.Common.CS10081OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Common.internal_static_protocol_CS10081_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Common.internal_static_protocol_CS10081_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Common.CS10081.class, protocol.Common.CS10081.Builder.class);
      }

      // Construct using protocol.Common.CS10081.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Common.internal_static_protocol_CS10081_descriptor;
      }

      @java.lang.Override
      public protocol.Common.CS10081 getDefaultInstanceForType() {
        return protocol.Common.CS10081.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Common.CS10081 build() {
        protocol.Common.CS10081 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Common.CS10081 buildPartial() {
        protocol.Common.CS10081 result = new protocol.Common.CS10081(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Common.CS10081) {
          return mergeFrom((protocol.Common.CS10081)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Common.CS10081 other) {
        if (other == protocol.Common.CS10081.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Common.CS10081 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Common.CS10081) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.CS10081)
    }

    // @@protoc_insertion_point(class_scope:protocol.CS10081)
    private static final protocol.Common.CS10081 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Common.CS10081();
    }

    public static protocol.Common.CS10081 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CS10081>
        PARSER = new com.google.protobuf.AbstractParser<CS10081>() {
      @java.lang.Override
      public CS10081 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CS10081(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS10081> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS10081> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Common.CS10081 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC10081OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.SC10081)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 serverTime = 1;</code>
     * @return Whether the serverTime field is set.
     */
    boolean hasServerTime();
    /**
     * <code>required int64 serverTime = 1;</code>
     * @return The serverTime.
     */
    long getServerTime();
  }
  /**
   * <pre>
   *返回服务器时间
   * </pre>
   *
   * Protobuf type {@code protocol.SC10081}
   */
  public  static final class SC10081 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.SC10081)
      SC10081OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC10081.newBuilder() to construct.
    private SC10081(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC10081() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SC10081();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC10081(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              serverTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Common.internal_static_protocol_SC10081_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Common.internal_static_protocol_SC10081_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Common.SC10081.class, protocol.Common.SC10081.Builder.class);
    }

    private int bitField0_;
    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private long serverTime_;
    /**
     * <code>required int64 serverTime = 1;</code>
     * @return Whether the serverTime field is set.
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 serverTime = 1;</code>
     * @return The serverTime.
     */
    public long getServerTime() {
      return serverTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, serverTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, serverTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Common.SC10081)) {
        return super.equals(obj);
      }
      protocol.Common.SC10081 other = (protocol.Common.SC10081) obj;

      if (hasServerTime() != other.hasServerTime()) return false;
      if (hasServerTime()) {
        if (getServerTime()
            != other.getServerTime()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServerTime()) {
        hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getServerTime());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Common.SC10081 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10081 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10081 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10081 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10081 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10081 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10081 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10081 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.SC10081 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10081 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.SC10081 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10081 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Common.SC10081 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *返回服务器时间
     * </pre>
     *
     * Protobuf type {@code protocol.SC10081}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.SC10081)
        protocol.Common.SC10081OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Common.internal_static_protocol_SC10081_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Common.internal_static_protocol_SC10081_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Common.SC10081.class, protocol.Common.SC10081.Builder.class);
      }

      // Construct using protocol.Common.SC10081.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serverTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Common.internal_static_protocol_SC10081_descriptor;
      }

      @java.lang.Override
      public protocol.Common.SC10081 getDefaultInstanceForType() {
        return protocol.Common.SC10081.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Common.SC10081 build() {
        protocol.Common.SC10081 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Common.SC10081 buildPartial() {
        protocol.Common.SC10081 result = new protocol.Common.SC10081(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverTime_ = serverTime_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Common.SC10081) {
          return mergeFrom((protocol.Common.SC10081)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Common.SC10081 other) {
        if (other == protocol.Common.SC10081.getDefaultInstance()) return this;
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasServerTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Common.SC10081 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Common.SC10081) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long serverTime_ ;
      /**
       * <code>required int64 serverTime = 1;</code>
       * @return Whether the serverTime field is set.
       */
      public boolean hasServerTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 serverTime = 1;</code>
       * @return The serverTime.
       */
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <code>required int64 serverTime = 1;</code>
       * @param value The serverTime to set.
       * @return This builder for chaining.
       */
      public Builder setServerTime(long value) {
        bitField0_ |= 0x00000001;
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 serverTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.SC10081)
    }

    // @@protoc_insertion_point(class_scope:protocol.SC10081)
    private static final protocol.Common.SC10081 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Common.SC10081();
    }

    public static protocol.Common.SC10081 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SC10081>
        PARSER = new com.google.protobuf.AbstractParser<SC10081>() {
      @java.lang.Override
      public SC10081 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC10081(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC10081> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC10081> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Common.SC10081 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CS10082OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.CS10082)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 serverTime = 1;</code>
     * @return Whether the serverTime field is set.
     */
    boolean hasServerTime();
    /**
     * <code>required int64 serverTime = 1;</code>
     * @return The serverTime.
     */
    long getServerTime();
  }
  /**
   * <pre>
   *心跳包
   * </pre>
   *
   * Protobuf type {@code protocol.CS10082}
   */
  public  static final class CS10082 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.CS10082)
      CS10082OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CS10082.newBuilder() to construct.
    private CS10082(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS10082() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CS10082();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CS10082(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              serverTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Common.internal_static_protocol_CS10082_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Common.internal_static_protocol_CS10082_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Common.CS10082.class, protocol.Common.CS10082.Builder.class);
    }

    private int bitField0_;
    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private long serverTime_;
    /**
     * <code>required int64 serverTime = 1;</code>
     * @return Whether the serverTime field is set.
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 serverTime = 1;</code>
     * @return The serverTime.
     */
    public long getServerTime() {
      return serverTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, serverTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, serverTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Common.CS10082)) {
        return super.equals(obj);
      }
      protocol.Common.CS10082 other = (protocol.Common.CS10082) obj;

      if (hasServerTime() != other.hasServerTime()) return false;
      if (hasServerTime()) {
        if (getServerTime()
            != other.getServerTime()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServerTime()) {
        hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getServerTime());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Common.CS10082 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.CS10082 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.CS10082 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.CS10082 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.CS10082 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.CS10082 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.CS10082 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.CS10082 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.CS10082 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Common.CS10082 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.CS10082 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.CS10082 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Common.CS10082 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *心跳包
     * </pre>
     *
     * Protobuf type {@code protocol.CS10082}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.CS10082)
        protocol.Common.CS10082OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Common.internal_static_protocol_CS10082_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Common.internal_static_protocol_CS10082_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Common.CS10082.class, protocol.Common.CS10082.Builder.class);
      }

      // Construct using protocol.Common.CS10082.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serverTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Common.internal_static_protocol_CS10082_descriptor;
      }

      @java.lang.Override
      public protocol.Common.CS10082 getDefaultInstanceForType() {
        return protocol.Common.CS10082.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Common.CS10082 build() {
        protocol.Common.CS10082 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Common.CS10082 buildPartial() {
        protocol.Common.CS10082 result = new protocol.Common.CS10082(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverTime_ = serverTime_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Common.CS10082) {
          return mergeFrom((protocol.Common.CS10082)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Common.CS10082 other) {
        if (other == protocol.Common.CS10082.getDefaultInstance()) return this;
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasServerTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Common.CS10082 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Common.CS10082) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long serverTime_ ;
      /**
       * <code>required int64 serverTime = 1;</code>
       * @return Whether the serverTime field is set.
       */
      public boolean hasServerTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 serverTime = 1;</code>
       * @return The serverTime.
       */
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <code>required int64 serverTime = 1;</code>
       * @param value The serverTime to set.
       * @return This builder for chaining.
       */
      public Builder setServerTime(long value) {
        bitField0_ |= 0x00000001;
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 serverTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.CS10082)
    }

    // @@protoc_insertion_point(class_scope:protocol.CS10082)
    private static final protocol.Common.CS10082 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Common.CS10082();
    }

    public static protocol.Common.CS10082 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CS10082>
        PARSER = new com.google.protobuf.AbstractParser<CS10082>() {
      @java.lang.Override
      public CS10082 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CS10082(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS10082> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS10082> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Common.CS10082 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC10083OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.SC10083)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 applicationId = 1;</code>
     * @return Whether the applicationId field is set.
     */
    boolean hasApplicationId();
    /**
     * <code>required int32 applicationId = 1;</code>
     * @return The applicationId.
     */
    int getApplicationId();

    /**
     * <pre>
     *附带参数
     * </pre>
     *
     * <code>repeated string parameter = 2;</code>
     * @return A list containing the parameter.
     */
    java.util.List<java.lang.String>
        getParameterList();
    /**
     * <pre>
     *附带参数
     * </pre>
     *
     * <code>repeated string parameter = 2;</code>
     * @return The count of parameter.
     */
    int getParameterCount();
    /**
     * <pre>
     *附带参数
     * </pre>
     *
     * <code>repeated string parameter = 2;</code>
     * @param index The index of the element to return.
     * @return The parameter at the given index.
     */
    java.lang.String getParameter(int index);
    /**
     * <pre>
     *附带参数
     * </pre>
     *
     * <code>repeated string parameter = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameter at the given index.
     */
    com.google.protobuf.ByteString
        getParameterBytes(int index);
  }
  /**
   * <pre>
   *返回公共公告信息
   * </pre>
   *
   * Protobuf type {@code protocol.SC10083}
   */
  public  static final class SC10083 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.SC10083)
      SC10083OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC10083.newBuilder() to construct.
    private SC10083(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC10083() {
      parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SC10083();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC10083(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              applicationId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                parameter_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              parameter_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          parameter_ = parameter_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Common.internal_static_protocol_SC10083_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Common.internal_static_protocol_SC10083_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Common.SC10083.class, protocol.Common.SC10083.Builder.class);
    }

    private int bitField0_;
    public static final int APPLICATIONID_FIELD_NUMBER = 1;
    private int applicationId_;
    /**
     * <code>required int32 applicationId = 1;</code>
     * @return Whether the applicationId field is set.
     */
    public boolean hasApplicationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 applicationId = 1;</code>
     * @return The applicationId.
     */
    public int getApplicationId() {
      return applicationId_;
    }

    public static final int PARAMETER_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList parameter_;
    /**
     * <pre>
     *附带参数
     * </pre>
     *
     * <code>repeated string parameter = 2;</code>
     * @return A list containing the parameter.
     */
    public com.google.protobuf.ProtocolStringList
        getParameterList() {
      return parameter_;
    }
    /**
     * <pre>
     *附带参数
     * </pre>
     *
     * <code>repeated string parameter = 2;</code>
     * @return The count of parameter.
     */
    public int getParameterCount() {
      return parameter_.size();
    }
    /**
     * <pre>
     *附带参数
     * </pre>
     *
     * <code>repeated string parameter = 2;</code>
     * @param index The index of the element to return.
     * @return The parameter at the given index.
     */
    public java.lang.String getParameter(int index) {
      return parameter_.get(index);
    }
    /**
     * <pre>
     *附带参数
     * </pre>
     *
     * <code>repeated string parameter = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameter at the given index.
     */
    public com.google.protobuf.ByteString
        getParameterBytes(int index) {
      return parameter_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasApplicationId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, applicationId_);
      }
      for (int i = 0; i < parameter_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, parameter_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, applicationId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameter_.size(); i++) {
          dataSize += computeStringSizeNoTag(parameter_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParameterList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Common.SC10083)) {
        return super.equals(obj);
      }
      protocol.Common.SC10083 other = (protocol.Common.SC10083) obj;

      if (hasApplicationId() != other.hasApplicationId()) return false;
      if (hasApplicationId()) {
        if (getApplicationId()
            != other.getApplicationId()) return false;
      }
      if (!getParameterList()
          .equals(other.getParameterList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasApplicationId()) {
        hash = (37 * hash) + APPLICATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getApplicationId();
      }
      if (getParameterCount() > 0) {
        hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
        hash = (53 * hash) + getParameterList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Common.SC10083 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10083 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10083 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10083 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10083 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Common.SC10083 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Common.SC10083 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10083 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.SC10083 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10083 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Common.SC10083 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Common.SC10083 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Common.SC10083 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *返回公共公告信息
     * </pre>
     *
     * Protobuf type {@code protocol.SC10083}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.SC10083)
        protocol.Common.SC10083OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Common.internal_static_protocol_SC10083_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Common.internal_static_protocol_SC10083_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Common.SC10083.class, protocol.Common.SC10083.Builder.class);
      }

      // Construct using protocol.Common.SC10083.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        applicationId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Common.internal_static_protocol_SC10083_descriptor;
      }

      @java.lang.Override
      public protocol.Common.SC10083 getDefaultInstanceForType() {
        return protocol.Common.SC10083.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Common.SC10083 build() {
        protocol.Common.SC10083 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Common.SC10083 buildPartial() {
        protocol.Common.SC10083 result = new protocol.Common.SC10083(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.applicationId_ = applicationId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          parameter_ = parameter_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.parameter_ = parameter_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Common.SC10083) {
          return mergeFrom((protocol.Common.SC10083)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Common.SC10083 other) {
        if (other == protocol.Common.SC10083.getDefaultInstance()) return this;
        if (other.hasApplicationId()) {
          setApplicationId(other.getApplicationId());
        }
        if (!other.parameter_.isEmpty()) {
          if (parameter_.isEmpty()) {
            parameter_ = other.parameter_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParameterIsMutable();
            parameter_.addAll(other.parameter_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasApplicationId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Common.SC10083 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Common.SC10083) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int applicationId_ ;
      /**
       * <code>required int32 applicationId = 1;</code>
       * @return Whether the applicationId field is set.
       */
      public boolean hasApplicationId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 applicationId = 1;</code>
       * @return The applicationId.
       */
      public int getApplicationId() {
        return applicationId_;
      }
      /**
       * <code>required int32 applicationId = 1;</code>
       * @param value The applicationId to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationId(int value) {
        bitField0_ |= 0x00000001;
        applicationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 applicationId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        applicationId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParameterIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          parameter_ = new com.google.protobuf.LazyStringArrayList(parameter_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @return A list containing the parameter.
       */
      public com.google.protobuf.ProtocolStringList
          getParameterList() {
        return parameter_.getUnmodifiableView();
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @return The count of parameter.
       */
      public int getParameterCount() {
        return parameter_.size();
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @param index The index of the element to return.
       * @return The parameter at the given index.
       */
      public java.lang.String getParameter(int index) {
        return parameter_.get(index);
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the parameter at the given index.
       */
      public com.google.protobuf.ByteString
          getParameterBytes(int index) {
        return parameter_.getByteString(index);
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @param index The index to set the value at.
       * @param value The parameter to set.
       * @return This builder for chaining.
       */
      public Builder setParameter(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterIsMutable();
        parameter_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @param value The parameter to add.
       * @return This builder for chaining.
       */
      public Builder addParameter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterIsMutable();
        parameter_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @param values The parameter to add.
       * @return This builder for chaining.
       */
      public Builder addAllParameter(
          java.lang.Iterable<java.lang.String> values) {
        ensureParameterIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameter_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameter() {
        parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *附带参数
       * </pre>
       *
       * <code>repeated string parameter = 2;</code>
       * @param value The bytes of the parameter to add.
       * @return This builder for chaining.
       */
      public Builder addParameterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterIsMutable();
        parameter_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.SC10083)
    }

    // @@protoc_insertion_point(class_scope:protocol.SC10083)
    private static final protocol.Common.SC10083 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Common.SC10083();
    }

    public static protocol.Common.SC10083 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SC10083>
        PARSER = new com.google.protobuf.AbstractParser<SC10083>() {
      @java.lang.Override
      public SC10083 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC10083(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC10083> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC10083> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Common.SC10083 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SC10080_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SC10080_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CS10081_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CS10081_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SC10081_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SC10081_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CS10082_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CS10082_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SC10083_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SC10083_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\010protocol\"%\n\007SC10080\022\032\n\022a" +
      "pplicationErrorId\030\001 \002(\005\"\t\n\007CS10081\"\035\n\007SC" +
      "10081\022\022\n\nserverTime\030\001 \002(\003\"\035\n\007CS10082\022\022\n\n" +
      "serverTime\030\001 \002(\003\"3\n\007SC10083\022\025\n\rapplicati" +
      "onId\030\001 \002(\005\022\021\n\tparameter\030\002 \003(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_SC10080_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_SC10080_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SC10080_descriptor,
        new java.lang.String[] { "ApplicationErrorId", });
    internal_static_protocol_CS10081_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_CS10081_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CS10081_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_SC10081_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_SC10081_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SC10081_descriptor,
        new java.lang.String[] { "ServerTime", });
    internal_static_protocol_CS10082_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_CS10082_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CS10082_descriptor,
        new java.lang.String[] { "ServerTime", });
    internal_static_protocol_SC10083_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protocol_SC10083_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SC10083_descriptor,
        new java.lang.String[] { "ApplicationId", "Parameter", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
