// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: equip.proto

package protocol;

public final class Equip {
  private Equip() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EquipInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.EquipInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 装备配置ID
     * </pre>
     *
     * <code>required int32 equipId = 1;</code>
     * @return Whether the equipId field is set.
     */
    boolean hasEquipId();
    /**
     * <pre>
     * 装备配置ID
     * </pre>
     *
     * <code>required int32 equipId = 1;</code>
     * @return The equipId.
     */
    int getEquipId();

    /**
     * <pre>
     * 装备潜能评级 (0未鉴定，1以上为评级)
     * </pre>
     *
     * <code>required int32 potentialGrade = 2;</code>
     * @return Whether the potentialGrade field is set.
     */
    boolean hasPotentialGrade();
    /**
     * <pre>
     * 装备潜能评级 (0未鉴定，1以上为评级)
     * </pre>
     *
     * <code>required int32 potentialGrade = 2;</code>
     * @return The potentialGrade.
     */
    int getPotentialGrade();

    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    java.util.List<protocol.Base.AttributeMap> 
        getPotentialAttributeMapList();
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    protocol.Base.AttributeMap getPotentialAttributeMap(int index);
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    int getPotentialAttributeMapCount();
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    java.util.List<? extends protocol.Base.AttributeMapOrBuilder> 
        getPotentialAttributeMapOrBuilderList();
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    protocol.Base.AttributeMapOrBuilder getPotentialAttributeMapOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 装备信息
   * </pre>
   *
   * Protobuf type {@code protocol.EquipInfo}
   */
  public  static final class EquipInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.EquipInfo)
      EquipInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EquipInfo.newBuilder() to construct.
    private EquipInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EquipInfo() {
      potentialAttributeMap_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EquipInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EquipInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              equipId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              potentialGrade_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                potentialAttributeMap_ = new java.util.ArrayList<protocol.Base.AttributeMap>();
                mutable_bitField0_ |= 0x00000004;
              }
              potentialAttributeMap_.add(
                  input.readMessage(protocol.Base.AttributeMap.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          potentialAttributeMap_ = java.util.Collections.unmodifiableList(potentialAttributeMap_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Equip.internal_static_protocol_EquipInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Equip.internal_static_protocol_EquipInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Equip.EquipInfo.class, protocol.Equip.EquipInfo.Builder.class);
    }

    private int bitField0_;
    public static final int EQUIPID_FIELD_NUMBER = 1;
    private int equipId_;
    /**
     * <pre>
     * 装备配置ID
     * </pre>
     *
     * <code>required int32 equipId = 1;</code>
     * @return Whether the equipId field is set.
     */
    public boolean hasEquipId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 装备配置ID
     * </pre>
     *
     * <code>required int32 equipId = 1;</code>
     * @return The equipId.
     */
    public int getEquipId() {
      return equipId_;
    }

    public static final int POTENTIALGRADE_FIELD_NUMBER = 2;
    private int potentialGrade_;
    /**
     * <pre>
     * 装备潜能评级 (0未鉴定，1以上为评级)
     * </pre>
     *
     * <code>required int32 potentialGrade = 2;</code>
     * @return Whether the potentialGrade field is set.
     */
    public boolean hasPotentialGrade() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 装备潜能评级 (0未鉴定，1以上为评级)
     * </pre>
     *
     * <code>required int32 potentialGrade = 2;</code>
     * @return The potentialGrade.
     */
    public int getPotentialGrade() {
      return potentialGrade_;
    }

    public static final int POTENTIALATTRIBUTEMAP_FIELD_NUMBER = 3;
    private java.util.List<protocol.Base.AttributeMap> potentialAttributeMap_;
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    public java.util.List<protocol.Base.AttributeMap> getPotentialAttributeMapList() {
      return potentialAttributeMap_;
    }
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    public java.util.List<? extends protocol.Base.AttributeMapOrBuilder> 
        getPotentialAttributeMapOrBuilderList() {
      return potentialAttributeMap_;
    }
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    public int getPotentialAttributeMapCount() {
      return potentialAttributeMap_.size();
    }
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    public protocol.Base.AttributeMap getPotentialAttributeMap(int index) {
      return potentialAttributeMap_.get(index);
    }
    /**
     * <pre>
     * 装备潜能属性
     * </pre>
     *
     * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
     */
    public protocol.Base.AttributeMapOrBuilder getPotentialAttributeMapOrBuilder(
        int index) {
      return potentialAttributeMap_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEquipId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPotentialGrade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPotentialAttributeMapCount(); i++) {
        if (!getPotentialAttributeMap(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, equipId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, potentialGrade_);
      }
      for (int i = 0; i < potentialAttributeMap_.size(); i++) {
        output.writeMessage(3, potentialAttributeMap_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, equipId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, potentialGrade_);
      }
      for (int i = 0; i < potentialAttributeMap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, potentialAttributeMap_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Equip.EquipInfo)) {
        return super.equals(obj);
      }
      protocol.Equip.EquipInfo other = (protocol.Equip.EquipInfo) obj;

      if (hasEquipId() != other.hasEquipId()) return false;
      if (hasEquipId()) {
        if (getEquipId()
            != other.getEquipId()) return false;
      }
      if (hasPotentialGrade() != other.hasPotentialGrade()) return false;
      if (hasPotentialGrade()) {
        if (getPotentialGrade()
            != other.getPotentialGrade()) return false;
      }
      if (!getPotentialAttributeMapList()
          .equals(other.getPotentialAttributeMapList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEquipId()) {
        hash = (37 * hash) + EQUIPID_FIELD_NUMBER;
        hash = (53 * hash) + getEquipId();
      }
      if (hasPotentialGrade()) {
        hash = (37 * hash) + POTENTIALGRADE_FIELD_NUMBER;
        hash = (53 * hash) + getPotentialGrade();
      }
      if (getPotentialAttributeMapCount() > 0) {
        hash = (37 * hash) + POTENTIALATTRIBUTEMAP_FIELD_NUMBER;
        hash = (53 * hash) + getPotentialAttributeMapList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Equip.EquipInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Equip.EquipInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Equip.EquipInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Equip.EquipInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Equip.EquipInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Equip.EquipInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Equip.EquipInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Equip.EquipInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Equip.EquipInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Equip.EquipInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Equip.EquipInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Equip.EquipInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Equip.EquipInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 装备信息
     * </pre>
     *
     * Protobuf type {@code protocol.EquipInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.EquipInfo)
        protocol.Equip.EquipInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Equip.internal_static_protocol_EquipInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Equip.internal_static_protocol_EquipInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Equip.EquipInfo.class, protocol.Equip.EquipInfo.Builder.class);
      }

      // Construct using protocol.Equip.EquipInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPotentialAttributeMapFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        equipId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        potentialGrade_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (potentialAttributeMapBuilder_ == null) {
          potentialAttributeMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          potentialAttributeMapBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Equip.internal_static_protocol_EquipInfo_descriptor;
      }

      @java.lang.Override
      public protocol.Equip.EquipInfo getDefaultInstanceForType() {
        return protocol.Equip.EquipInfo.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Equip.EquipInfo build() {
        protocol.Equip.EquipInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Equip.EquipInfo buildPartial() {
        protocol.Equip.EquipInfo result = new protocol.Equip.EquipInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.equipId_ = equipId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.potentialGrade_ = potentialGrade_;
          to_bitField0_ |= 0x00000002;
        }
        if (potentialAttributeMapBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            potentialAttributeMap_ = java.util.Collections.unmodifiableList(potentialAttributeMap_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.potentialAttributeMap_ = potentialAttributeMap_;
        } else {
          result.potentialAttributeMap_ = potentialAttributeMapBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Equip.EquipInfo) {
          return mergeFrom((protocol.Equip.EquipInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Equip.EquipInfo other) {
        if (other == protocol.Equip.EquipInfo.getDefaultInstance()) return this;
        if (other.hasEquipId()) {
          setEquipId(other.getEquipId());
        }
        if (other.hasPotentialGrade()) {
          setPotentialGrade(other.getPotentialGrade());
        }
        if (potentialAttributeMapBuilder_ == null) {
          if (!other.potentialAttributeMap_.isEmpty()) {
            if (potentialAttributeMap_.isEmpty()) {
              potentialAttributeMap_ = other.potentialAttributeMap_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePotentialAttributeMapIsMutable();
              potentialAttributeMap_.addAll(other.potentialAttributeMap_);
            }
            onChanged();
          }
        } else {
          if (!other.potentialAttributeMap_.isEmpty()) {
            if (potentialAttributeMapBuilder_.isEmpty()) {
              potentialAttributeMapBuilder_.dispose();
              potentialAttributeMapBuilder_ = null;
              potentialAttributeMap_ = other.potentialAttributeMap_;
              bitField0_ = (bitField0_ & ~0x00000004);
              potentialAttributeMapBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPotentialAttributeMapFieldBuilder() : null;
            } else {
              potentialAttributeMapBuilder_.addAllMessages(other.potentialAttributeMap_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasEquipId()) {
          return false;
        }
        if (!hasPotentialGrade()) {
          return false;
        }
        for (int i = 0; i < getPotentialAttributeMapCount(); i++) {
          if (!getPotentialAttributeMap(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Equip.EquipInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Equip.EquipInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int equipId_ ;
      /**
       * <pre>
       * 装备配置ID
       * </pre>
       *
       * <code>required int32 equipId = 1;</code>
       * @return Whether the equipId field is set.
       */
      public boolean hasEquipId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 装备配置ID
       * </pre>
       *
       * <code>required int32 equipId = 1;</code>
       * @return The equipId.
       */
      public int getEquipId() {
        return equipId_;
      }
      /**
       * <pre>
       * 装备配置ID
       * </pre>
       *
       * <code>required int32 equipId = 1;</code>
       * @param value The equipId to set.
       * @return This builder for chaining.
       */
      public Builder setEquipId(int value) {
        bitField0_ |= 0x00000001;
        equipId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 装备配置ID
       * </pre>
       *
       * <code>required int32 equipId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEquipId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        equipId_ = 0;
        onChanged();
        return this;
      }

      private int potentialGrade_ ;
      /**
       * <pre>
       * 装备潜能评级 (0未鉴定，1以上为评级)
       * </pre>
       *
       * <code>required int32 potentialGrade = 2;</code>
       * @return Whether the potentialGrade field is set.
       */
      public boolean hasPotentialGrade() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 装备潜能评级 (0未鉴定，1以上为评级)
       * </pre>
       *
       * <code>required int32 potentialGrade = 2;</code>
       * @return The potentialGrade.
       */
      public int getPotentialGrade() {
        return potentialGrade_;
      }
      /**
       * <pre>
       * 装备潜能评级 (0未鉴定，1以上为评级)
       * </pre>
       *
       * <code>required int32 potentialGrade = 2;</code>
       * @param value The potentialGrade to set.
       * @return This builder for chaining.
       */
      public Builder setPotentialGrade(int value) {
        bitField0_ |= 0x00000002;
        potentialGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 装备潜能评级 (0未鉴定，1以上为评级)
       * </pre>
       *
       * <code>required int32 potentialGrade = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPotentialGrade() {
        bitField0_ = (bitField0_ & ~0x00000002);
        potentialGrade_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<protocol.Base.AttributeMap> potentialAttributeMap_ =
        java.util.Collections.emptyList();
      private void ensurePotentialAttributeMapIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          potentialAttributeMap_ = new java.util.ArrayList<protocol.Base.AttributeMap>(potentialAttributeMap_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Base.AttributeMap, protocol.Base.AttributeMap.Builder, protocol.Base.AttributeMapOrBuilder> potentialAttributeMapBuilder_;

      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public java.util.List<protocol.Base.AttributeMap> getPotentialAttributeMapList() {
        if (potentialAttributeMapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(potentialAttributeMap_);
        } else {
          return potentialAttributeMapBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public int getPotentialAttributeMapCount() {
        if (potentialAttributeMapBuilder_ == null) {
          return potentialAttributeMap_.size();
        } else {
          return potentialAttributeMapBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public protocol.Base.AttributeMap getPotentialAttributeMap(int index) {
        if (potentialAttributeMapBuilder_ == null) {
          return potentialAttributeMap_.get(index);
        } else {
          return potentialAttributeMapBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder setPotentialAttributeMap(
          int index, protocol.Base.AttributeMap value) {
        if (potentialAttributeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePotentialAttributeMapIsMutable();
          potentialAttributeMap_.set(index, value);
          onChanged();
        } else {
          potentialAttributeMapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder setPotentialAttributeMap(
          int index, protocol.Base.AttributeMap.Builder builderForValue) {
        if (potentialAttributeMapBuilder_ == null) {
          ensurePotentialAttributeMapIsMutable();
          potentialAttributeMap_.set(index, builderForValue.build());
          onChanged();
        } else {
          potentialAttributeMapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder addPotentialAttributeMap(protocol.Base.AttributeMap value) {
        if (potentialAttributeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePotentialAttributeMapIsMutable();
          potentialAttributeMap_.add(value);
          onChanged();
        } else {
          potentialAttributeMapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder addPotentialAttributeMap(
          int index, protocol.Base.AttributeMap value) {
        if (potentialAttributeMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePotentialAttributeMapIsMutable();
          potentialAttributeMap_.add(index, value);
          onChanged();
        } else {
          potentialAttributeMapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder addPotentialAttributeMap(
          protocol.Base.AttributeMap.Builder builderForValue) {
        if (potentialAttributeMapBuilder_ == null) {
          ensurePotentialAttributeMapIsMutable();
          potentialAttributeMap_.add(builderForValue.build());
          onChanged();
        } else {
          potentialAttributeMapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder addPotentialAttributeMap(
          int index, protocol.Base.AttributeMap.Builder builderForValue) {
        if (potentialAttributeMapBuilder_ == null) {
          ensurePotentialAttributeMapIsMutable();
          potentialAttributeMap_.add(index, builderForValue.build());
          onChanged();
        } else {
          potentialAttributeMapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder addAllPotentialAttributeMap(
          java.lang.Iterable<? extends protocol.Base.AttributeMap> values) {
        if (potentialAttributeMapBuilder_ == null) {
          ensurePotentialAttributeMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, potentialAttributeMap_);
          onChanged();
        } else {
          potentialAttributeMapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder clearPotentialAttributeMap() {
        if (potentialAttributeMapBuilder_ == null) {
          potentialAttributeMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          potentialAttributeMapBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public Builder removePotentialAttributeMap(int index) {
        if (potentialAttributeMapBuilder_ == null) {
          ensurePotentialAttributeMapIsMutable();
          potentialAttributeMap_.remove(index);
          onChanged();
        } else {
          potentialAttributeMapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public protocol.Base.AttributeMap.Builder getPotentialAttributeMapBuilder(
          int index) {
        return getPotentialAttributeMapFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public protocol.Base.AttributeMapOrBuilder getPotentialAttributeMapOrBuilder(
          int index) {
        if (potentialAttributeMapBuilder_ == null) {
          return potentialAttributeMap_.get(index);  } else {
          return potentialAttributeMapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public java.util.List<? extends protocol.Base.AttributeMapOrBuilder> 
           getPotentialAttributeMapOrBuilderList() {
        if (potentialAttributeMapBuilder_ != null) {
          return potentialAttributeMapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(potentialAttributeMap_);
        }
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public protocol.Base.AttributeMap.Builder addPotentialAttributeMapBuilder() {
        return getPotentialAttributeMapFieldBuilder().addBuilder(
            protocol.Base.AttributeMap.getDefaultInstance());
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public protocol.Base.AttributeMap.Builder addPotentialAttributeMapBuilder(
          int index) {
        return getPotentialAttributeMapFieldBuilder().addBuilder(
            index, protocol.Base.AttributeMap.getDefaultInstance());
      }
      /**
       * <pre>
       * 装备潜能属性
       * </pre>
       *
       * <code>repeated .protocol.AttributeMap potentialAttributeMap = 3;</code>
       */
      public java.util.List<protocol.Base.AttributeMap.Builder> 
           getPotentialAttributeMapBuilderList() {
        return getPotentialAttributeMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Base.AttributeMap, protocol.Base.AttributeMap.Builder, protocol.Base.AttributeMapOrBuilder> 
          getPotentialAttributeMapFieldBuilder() {
        if (potentialAttributeMapBuilder_ == null) {
          potentialAttributeMapBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.Base.AttributeMap, protocol.Base.AttributeMap.Builder, protocol.Base.AttributeMapOrBuilder>(
                  potentialAttributeMap_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          potentialAttributeMap_ = null;
        }
        return potentialAttributeMapBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.EquipInfo)
    }

    // @@protoc_insertion_point(class_scope:protocol.EquipInfo)
    private static final protocol.Equip.EquipInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Equip.EquipInfo();
    }

    public static protocol.Equip.EquipInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EquipInfo>
        PARSER = new com.google.protobuf.AbstractParser<EquipInfo>() {
      @java.lang.Override
      public EquipInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EquipInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EquipInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EquipInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Equip.EquipInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC11100OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.SC11100)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    java.util.List<protocol.Equip.EquipInfo> 
        getEquipsList();
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    protocol.Equip.EquipInfo getEquips(int index);
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    int getEquipsCount();
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    java.util.List<? extends protocol.Equip.EquipInfoOrBuilder> 
        getEquipsOrBuilderList();
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    protocol.Equip.EquipInfoOrBuilder getEquipsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 推送已穿戴的装备列表
   * </pre>
   *
   * Protobuf type {@code protocol.SC11100}
   */
  public  static final class SC11100 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.SC11100)
      SC11100OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SC11100.newBuilder() to construct.
    private SC11100(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC11100() {
      equips_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SC11100();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SC11100(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                equips_ = new java.util.ArrayList<protocol.Equip.EquipInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              equips_.add(
                  input.readMessage(protocol.Equip.EquipInfo.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          equips_ = java.util.Collections.unmodifiableList(equips_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Equip.internal_static_protocol_SC11100_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Equip.internal_static_protocol_SC11100_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Equip.SC11100.class, protocol.Equip.SC11100.Builder.class);
    }

    public static final int EQUIPS_FIELD_NUMBER = 1;
    private java.util.List<protocol.Equip.EquipInfo> equips_;
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    public java.util.List<protocol.Equip.EquipInfo> getEquipsList() {
      return equips_;
    }
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    public java.util.List<? extends protocol.Equip.EquipInfoOrBuilder> 
        getEquipsOrBuilderList() {
      return equips_;
    }
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    public int getEquipsCount() {
      return equips_.size();
    }
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    public protocol.Equip.EquipInfo getEquips(int index) {
      return equips_.get(index);
    }
    /**
     * <pre>
     * 装备列表
     * </pre>
     *
     * <code>repeated .protocol.EquipInfo equips = 1;</code>
     */
    public protocol.Equip.EquipInfoOrBuilder getEquipsOrBuilder(
        int index) {
      return equips_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getEquipsCount(); i++) {
        if (!getEquips(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < equips_.size(); i++) {
        output.writeMessage(1, equips_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < equips_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, equips_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Equip.SC11100)) {
        return super.equals(obj);
      }
      protocol.Equip.SC11100 other = (protocol.Equip.SC11100) obj;

      if (!getEquipsList()
          .equals(other.getEquipsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEquipsCount() > 0) {
        hash = (37 * hash) + EQUIPS_FIELD_NUMBER;
        hash = (53 * hash) + getEquipsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Equip.SC11100 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Equip.SC11100 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Equip.SC11100 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Equip.SC11100 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Equip.SC11100 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Equip.SC11100 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Equip.SC11100 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Equip.SC11100 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Equip.SC11100 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Equip.SC11100 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Equip.SC11100 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Equip.SC11100 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Equip.SC11100 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 推送已穿戴的装备列表
     * </pre>
     *
     * Protobuf type {@code protocol.SC11100}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.SC11100)
        protocol.Equip.SC11100OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Equip.internal_static_protocol_SC11100_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Equip.internal_static_protocol_SC11100_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Equip.SC11100.class, protocol.Equip.SC11100.Builder.class);
      }

      // Construct using protocol.Equip.SC11100.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEquipsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (equipsBuilder_ == null) {
          equips_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          equipsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Equip.internal_static_protocol_SC11100_descriptor;
      }

      @java.lang.Override
      public protocol.Equip.SC11100 getDefaultInstanceForType() {
        return protocol.Equip.SC11100.getDefaultInstance();
      }

      @java.lang.Override
      public protocol.Equip.SC11100 build() {
        protocol.Equip.SC11100 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocol.Equip.SC11100 buildPartial() {
        protocol.Equip.SC11100 result = new protocol.Equip.SC11100(this);
        int from_bitField0_ = bitField0_;
        if (equipsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            equips_ = java.util.Collections.unmodifiableList(equips_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.equips_ = equips_;
        } else {
          result.equips_ = equipsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Equip.SC11100) {
          return mergeFrom((protocol.Equip.SC11100)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Equip.SC11100 other) {
        if (other == protocol.Equip.SC11100.getDefaultInstance()) return this;
        if (equipsBuilder_ == null) {
          if (!other.equips_.isEmpty()) {
            if (equips_.isEmpty()) {
              equips_ = other.equips_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEquipsIsMutable();
              equips_.addAll(other.equips_);
            }
            onChanged();
          }
        } else {
          if (!other.equips_.isEmpty()) {
            if (equipsBuilder_.isEmpty()) {
              equipsBuilder_.dispose();
              equipsBuilder_ = null;
              equips_ = other.equips_;
              bitField0_ = (bitField0_ & ~0x00000001);
              equipsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEquipsFieldBuilder() : null;
            } else {
              equipsBuilder_.addAllMessages(other.equips_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getEquipsCount(); i++) {
          if (!getEquips(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Equip.SC11100 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Equip.SC11100) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protocol.Equip.EquipInfo> equips_ =
        java.util.Collections.emptyList();
      private void ensureEquipsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          equips_ = new java.util.ArrayList<protocol.Equip.EquipInfo>(equips_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Equip.EquipInfo, protocol.Equip.EquipInfo.Builder, protocol.Equip.EquipInfoOrBuilder> equipsBuilder_;

      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public java.util.List<protocol.Equip.EquipInfo> getEquipsList() {
        if (equipsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(equips_);
        } else {
          return equipsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public int getEquipsCount() {
        if (equipsBuilder_ == null) {
          return equips_.size();
        } else {
          return equipsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public protocol.Equip.EquipInfo getEquips(int index) {
        if (equipsBuilder_ == null) {
          return equips_.get(index);
        } else {
          return equipsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder setEquips(
          int index, protocol.Equip.EquipInfo value) {
        if (equipsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipsIsMutable();
          equips_.set(index, value);
          onChanged();
        } else {
          equipsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder setEquips(
          int index, protocol.Equip.EquipInfo.Builder builderForValue) {
        if (equipsBuilder_ == null) {
          ensureEquipsIsMutable();
          equips_.set(index, builderForValue.build());
          onChanged();
        } else {
          equipsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder addEquips(protocol.Equip.EquipInfo value) {
        if (equipsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipsIsMutable();
          equips_.add(value);
          onChanged();
        } else {
          equipsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder addEquips(
          int index, protocol.Equip.EquipInfo value) {
        if (equipsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipsIsMutable();
          equips_.add(index, value);
          onChanged();
        } else {
          equipsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder addEquips(
          protocol.Equip.EquipInfo.Builder builderForValue) {
        if (equipsBuilder_ == null) {
          ensureEquipsIsMutable();
          equips_.add(builderForValue.build());
          onChanged();
        } else {
          equipsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder addEquips(
          int index, protocol.Equip.EquipInfo.Builder builderForValue) {
        if (equipsBuilder_ == null) {
          ensureEquipsIsMutable();
          equips_.add(index, builderForValue.build());
          onChanged();
        } else {
          equipsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder addAllEquips(
          java.lang.Iterable<? extends protocol.Equip.EquipInfo> values) {
        if (equipsBuilder_ == null) {
          ensureEquipsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, equips_);
          onChanged();
        } else {
          equipsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder clearEquips() {
        if (equipsBuilder_ == null) {
          equips_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          equipsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public Builder removeEquips(int index) {
        if (equipsBuilder_ == null) {
          ensureEquipsIsMutable();
          equips_.remove(index);
          onChanged();
        } else {
          equipsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public protocol.Equip.EquipInfo.Builder getEquipsBuilder(
          int index) {
        return getEquipsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public protocol.Equip.EquipInfoOrBuilder getEquipsOrBuilder(
          int index) {
        if (equipsBuilder_ == null) {
          return equips_.get(index);  } else {
          return equipsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public java.util.List<? extends protocol.Equip.EquipInfoOrBuilder> 
           getEquipsOrBuilderList() {
        if (equipsBuilder_ != null) {
          return equipsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(equips_);
        }
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public protocol.Equip.EquipInfo.Builder addEquipsBuilder() {
        return getEquipsFieldBuilder().addBuilder(
            protocol.Equip.EquipInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public protocol.Equip.EquipInfo.Builder addEquipsBuilder(
          int index) {
        return getEquipsFieldBuilder().addBuilder(
            index, protocol.Equip.EquipInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * 装备列表
       * </pre>
       *
       * <code>repeated .protocol.EquipInfo equips = 1;</code>
       */
      public java.util.List<protocol.Equip.EquipInfo.Builder> 
           getEquipsBuilderList() {
        return getEquipsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Equip.EquipInfo, protocol.Equip.EquipInfo.Builder, protocol.Equip.EquipInfoOrBuilder> 
          getEquipsFieldBuilder() {
        if (equipsBuilder_ == null) {
          equipsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.Equip.EquipInfo, protocol.Equip.EquipInfo.Builder, protocol.Equip.EquipInfoOrBuilder>(
                  equips_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          equips_ = null;
        }
        return equipsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.SC11100)
    }

    // @@protoc_insertion_point(class_scope:protocol.SC11100)
    private static final protocol.Equip.SC11100 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Equip.SC11100();
    }

    public static protocol.Equip.SC11100 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SC11100>
        PARSER = new com.google.protobuf.AbstractParser<SC11100>() {
      @java.lang.Override
      public SC11100 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC11100(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC11100> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC11100> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocol.Equip.SC11100 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_EquipInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_EquipInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SC11100_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SC11100_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013equip.proto\022\010protocol\032\nbase.proto\"k\n\tE" +
      "quipInfo\022\017\n\007equipId\030\001 \002(\005\022\026\n\016potentialGr" +
      "ade\030\002 \002(\005\0225\n\025potentialAttributeMap\030\003 \003(\013" +
      "2\026.protocol.AttributeMap\".\n\007SC11100\022#\n\006e" +
      "quips\030\001 \003(\0132\023.protocol.EquipInfo"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Base.getDescriptor(),
        });
    internal_static_protocol_EquipInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_EquipInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_EquipInfo_descriptor,
        new java.lang.String[] { "EquipId", "PotentialGrade", "PotentialAttributeMap", });
    internal_static_protocol_SC11100_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_SC11100_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SC11100_descriptor,
        new java.lang.String[] { "Equips", });
    protocol.Base.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
